### ISSUE TITLE
bug handling small program with a `while` loop

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#100]
jq has no problem handling the appended program with a `while` loop.  I've not been able to pinpoint the problem as adding `debug` statements in various spots was not illuminating in the way I'd expect.

```
$ ~/github/gojq/gojq --version
gojq 0.12.4 (rev: d64a861/go1.16)

$ ~/github/gojq/gojq -n -f humbles.gojq
gojq: expected an array but got: object ({"h":1,"queue":[2,3,5,7]})

$ gojq --version
gojq 0.12.4 (rev: 244f9f7/go1.16.4)

$ gojq -n -f humbles.gojq
gojq: expected an array but got: object ({"h":1,"queue":[2,3,5,7]})

$ jq -n -f humbles.gojq
45
```

The program:

```
def humbles($digits):
  def update:
    .[0] as $h
    | ([$h * 3, $h * 5, $h * 7] | map(select(tostring|length <= $digits))) as $next
    | (.[1:] + [$h * 2] + $next) | sort;
  def trim: if length <= 1 then . elif .[0]==.[1] then .[1:]|trim else . end;

  { h: 1, queue: [2,3,5,7]}
  | while( (.h|tostring|length) <= $digits;
          (.queue |= trim)
	  | .h = .queue[0]
	  | (.queue |= update) )
    | .h;

[humbles(2)] | length
```

**Comment by itchyny** [comment]
Okay, I'll take a look soon. This problem is caused by the implementation where declared functions always have priority over arguments; `def f(g): def g: 1; g; f(2)` works but `def g: 1; def f(g): g; f(2)` does not.

**Comment by pkoppstein** [comment]
Wow, that is a very big problem, not least because it seems to violate the shadowing principle.

But I'm not sure how that's relevant here, since in the 'humbles' program, the only named argument is "$digits" and there is no `def digits:` anywhere in sight.

Btw, I rewrote `humbles/1` to use `foreach` instead of `while`, but to no avail

Thanks!

**Comment by itchyny** [comment]
The problem exists in `update` because it conflicts with the argument of builtin `while/2`.

**Comment by itchyny** [comment]
Fixed the issue.

**Comment by pkoppstein** [comment]
> Fixed the issue.

That was quick!  Congratulations.

On a somewhat different topic (though also what I think of as a core issue), I was thinking that if addressing memory management issues comprehensively is going to be too difficult in the foreseeable future, then perhaps a worthwhile alternative to consider would be to provide Go implementations of some useful functions that cannot presently be implemented efficiently in pure `gojq`. Perhaps `bsearch` would be one such amongst existing functions. Amongst others, two come to mind: `merge/1` for merging two sorted lists, and PRNG functions.  In the stedolan/jq world, Eric Brinkman did some wonderful work that was never incorporated -- see in particular 
https://github.com/erikbrinkman/jq/commit/01a7d694ad38809fdd67718f78c8b56c5886b81f
and more generally
https://github.com/stedolan/jq/issues/1038
