### ISSUE TITLE
small bug: tilde expansion with -L

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#103]
When using the -L option, single-quotes placed around a tilde directory ("~/") on the command line
are improperly preventing tilde-expansion:
```
$ jq -L ~/github/jqMaster/tests/modules -cMn  'include "c"; [a, c]'
[0,"acmehbah"]

$ jq -L '~/github/jqMaster/tests/modules' -cMn  'include "c"; [a, c]'
[0,"acmehbah"]

$ gojq -L ~/github/jqMaster/tests/modules -cMn  'include "c"; [a, c]'
[0,"acmehbah"]

$ gojq -L '~/github/jqMaster/tests/modules' -cMn  'include "c"; [a, c]'
gojq: compile error: module not found: "c"
```

**Comment by itchyny** [comment]
Command expanding `~` in program path arguments is not a good command behavior in general. It is a task handled by shell, and none of any basic linux commands supports this as far as I know.

**Comment by pkoppstein** [comment]
Yes, but -L is indeed special.  From the jq manual:

> Paths in the a search path are subject to various substitutions.

> For paths starting with "~/", the user's home directory is substituted for "~".

**Comment by itchyny** [comment]
Okay, I'll implement it.

**Comment by pkoppstein** [comment]
Small thorns are often the most irritating.

Thanks.
