### ISSUE TITLE
jq/gojq discrepancy in handling of "compile error"

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#106]
For jq, `{(0):1}`is a compile-time error:
```
jq -n 'empty|{(0):1}'
jq: error: Cannot use number (0) as object key at <top-level>, line 1:
empty|{(0):1}       
jq: 1 compile error
```

But for gojq:
```
$ gojqMaster -n 'empty|{(0):1}'
$
```
Are such discrepancies "bugs"?

**Comment by itchyny** [comment]
After fixing this specific query, you'll report `empty|{(0+0):1}`. Constant folding is quite complex and unlikely implemented in gojq. Also I think the behavior of jq is halfway, it does not fold constant variables; `1 as $x|empty|{($x):1}`. After all this kind of feature creates wired specs, I'd rather prefer letting the check on runtime.

**Comment by pkoppstein** [comment]
@itchyny - Thanks for the clarification.  As I've already indicated, I never thought of this kind of discrepancy as a "bug" or even as particularly important (though it does frustrate automated testing), but I would like to point out that since there's an obvious difference between expressions such as `{(J):1}` on the one hand (where J is a literal JSON expression), and `{(E):1}` (where E is a non-JSON expression) on the other, it seems to me that jq's creators have found a very reasonable and principled way to balance the goals of avoiding complexity and providing some compile-time analysis.
