### ISSUE TITLE
jq halt_error behaviour difference

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#109]
jq 1.6
```sh
$ jq -n '"abc" | halt_error' 2>&1 | hexdump -C
00000000  61 62 63                                          |abc|
00000003
```
jq master (d18b2d078c2383d9472d0a0a226e07009025574f)
```sh
$ ./jq -n '"abc" | halt_error' 2>&1 | hexdump -C
00000000  6a 71 3a 20 65 72 72 6f  72 3a 20 61 62 63        |jq: error: abc|
0000000e
```
gojq main
```sh
$ ./gojq -n '"abc" | halt_error' 2>&1 | hexdump -C
00000000  67 6f 6a 71 3a 20 65 72  72 6f 72 3a 20 61 62 63  |gojq: error: abc|
00000010  0a                                                |.|
00000011
```

jq `halt_error` documentation currently says
> Stops the jq program with no further outputs. The input will be printed on stderr as raw output (i.e., strings will not have double quotes) with no decoration, not even a newline.

There is an issue about jq master adding a prefix at the moment https://github.com/stedolan/jq/issues/1902

`null` input to `halt_error` seems behave the same as jq, prints nothing.

**Comment by itchyny** [comment]
Nice find. I fixed this.
