### ISSUE TITLE
Considering adding a flag to write output into file

### ISSUE THREAD

**Issue by zhouhaibing089** [itchyny/gojq#110]
This project is really awesome, and I find a lot of joy when using it. Thanks!

I'm now trying to integrate this tool into our CI/CD pipeline flow, and one thing that is nice to have is to add a flag so that it can write output into file. This is especially needed when I want to use this image `ghcr.io/itchyny/gojq:0` because the base image doesn't have `bash` or `sh`.

If you think this is reasonable to add, I can try to see how can I help, otherwise I can just build another image on my own.

**Comment by itchyny** [comment]
You can't redirect the output of docker run in your CI/CD pipeline? If the base image is alpine, does it solve the problem? In any case you will need to bind volume mounts.

**Comment by zhouhaibing089** [comment]
> You can't redirect the output of docker run in your CI/CD pipeline?

I can't - The CICD pipeline is running as kubernetes Pods so it is not like `docker run` somewhere, but rather the container image is used to spin up pods.

> If the base image is alpine, does it solve the problem?

This definitely does. All it needs is bash(or sh). And I think it is also helpful to have `echo`/`cat` so the examples can be run from container as well.

I like the small footprint by using `gcr.io/distroless/static:nonroot` as base image, and it is also more secure when it doesn't have other additional binaries. In that sense, a flag seems to be more reasonable. The downside might be introducing something that doesn't exist in `jq` itself.

**Comment by pkoppstein** [comment]
One of the reasons such a flag is not supported by jq is that it introduces the same complexities as would be introduced by a sed-like -i flag.  That is, what to do if the specified output file is being read?  It's not that this can't be handled, it's that it introduces some additional complexity that goes counter to jq's "minimalist" tendencies, in support of a set of features (to sponge or not to sponge) for which at least one reasonable alternative exists. 

Another reason is that there was a principle that favored jq filters over command-line options, the idea being that jq ought to have enhanced file-handling alternatives.

**Comment by zhouhaibing089** [comment]
Thanks for explaining the reasons!

I looked at how other tools are using distroless images,  and one example is https://github.com/sigstore/cosign/blob/749cd293ebcc6d6340ff5a9e7ad334b323d197ce/.ko.yaml#L17.

Maybe `gcr.io/distroless/static:debug` is also a good fit for gojq.

**Comment by itchyny** [comment]
Switched to the debug image.
