### ISSUE TITLE
jq/gojq discrepancy: TZ and daylight savings

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#111]
I believe the following discrepancies are the result of incorrect behavior by stedolan/jq.  If so, then it would I think be appropriate and helpful to include a note accordingly on gojq's README page.
```
#!/bin/bash

pgm='1628117712 | strflocaltime("%Y-%m-%dT%H:%M:%S %Z")'

for TZ in America/New_York Europe/Madrid ; do
  for jq in jq gojq ; do
      echo "$TZ $jq =>" $(TZ="$TZ" $jq -nR "$pgm")
  done
  echo ""
done
```
Output:
```
America/New_York jq => "2021-08-04T18:55:12 EST"
America/New_York gojq => "2021-08-04T18:55:12 EDT"

Europe/Madrid jq => "2021-08-05T00:55:12 CET"
Europe/Madrid gojq => "2021-08-05T00:55:12 CEST"
```

**Comment by itchyny** [comment]
This looks like a bug of jq, as pull request proposed by https://github.com/stedolan/jq/pull/2202.

**Comment by itchyny** [comment]
Memo: `TZ=Europe/London gojq -n 'now | strflocaltime("%Z")'` should be `"BST"`, not `"GMT"`.
