### ISSUE TITLE
[Enhancement]: optimized version of `walk`

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#112]
Appended is an optimized def of `walk`, which produces measurable benefits for gojq.
In the first test I concocted, it reduced "maximum resident set size" by about 7%, and u+s by about 4%.

(Of course, it also produces benefits for jq, but there are other
much higher priority enhancements for jq waiting in the queue.)

```
# Apply f to composite entities recursively, and to atoms
def walk(f):
  def w:
    if type == "object"
    then . as $in
    | reduce keys[] as $key
        ( {}; . + { ($key):  ($in[$key] | w) } ) | f
    elif type == "array" then map( w ) | f
    else f
    end;
  w;
```

**Comment by itchyny** [comment]
The w function is not tail call, but produces smaller code, leads to performance improvement worth enough to include. Thanks.
