### ISSUE TITLE
error/0 and error/1 behavior difference

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#113]
jq 1.6 and  master does not allow string input or argument
```sh
$ jq -n '1 | error'
jq: error (at <unknown>) (not a string): 1
$ jq -n 'error(1)'
jq: error (at <unknown>) (not a string): 1
```
gojq
```sh
$ ./gojq -n '1 | error'
gojq: error: 1
$ ./gojq -n 'error(1)'
gojq: error: 1
```
I kind of like that it's possible to throw non-string values and catch them. But maybe the difference should be documented?

**Comment by itchyny** [comment]
The exit code is same, and the behavior of gojq looks better. I think fixing it to type error does not change the behavior.

**Comment by wader** [comment]
Agreeing, created a PR to document the difference.
