### ISSUE TITLE
TZ and %Z

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#116]
Consider:
```
tz=Europe/Madrid
for jq in gojq gojqMaster ; do
  echo
  $jq --version
  TZ=$tz $jq -n '
  {"@timestamp": "2020-05-04T18:02:13Z"}
  | .["@timestamp"]
  | fromdateiso8601   # converts to seconds
  | gmtime
  | strftime("%Y-%m-%dT%H:%M:%S%Z")
'
done
```

This produces:
```
gojq 0.12.4 (rev: 244f9f7/go1.16.4)
"2020-05-04T18:02:13UTC"

gojq 0.12.4 (rev: 4440cde/go1.16)
"2020-05-04T18:02:13UTC"
```

I believe that the timezone in the result should be either CET or even better CEST, with adjustments of course to the remainder of the string.  

For reference:

> Since 1996, European Summer Time has been observed between 01:00 UTC (02:00 CET and 03:00 CEST) on the last Sunday of March, and 01:00 UTC on the last Sunday of October [wikipedia]

**Comment by itchyny** [comment]
`strflocaltime` does handle this

**Comment by pkoppstein** [comment]
@itchyny - My apologies -- the writeup of the problem was wrong.  Here is what I should have written:

Consider:
```
tz=Europe/Madrid

for jq in gojq gojqMaster ; do
  echo
  $jq --version
  TZ=$tz $jq -n '

  {"@timestamp": "2020-05-04T18:02:13Z"}
  | .["@timestamp"]
  | fromdateiso8601   # converts to seconds
  | gmtime
  | strflocaltime("%Y-%m-%dT%H:%M:%S%Z")
'
done
```
Output:
```

gojq 0.12.4 (rev: 244f9f7/go1.16.4)
"2020-05-04T18:02:13CEST"

gojq 0.12.4 (rev: 4440cde/go1.16)
"2020-05-04T18:02:13CEST"
```

Notice that the "%Z" substitution is correct but that the time has not been adjusted properly:
```
CET = Z+1
CEST=Z+2
```

Incidentally, when you have time, could you please review
https://github.com/stedolan/jq/wiki/Regarding-gojq

**Comment by itchyny** [comment]
When you convert a specific date time between timezones, pass the unix epoch to `strflocaltime` directly. It converts `18:02:13Z` to `20:02:13CEST`. What `gmtime` does is converting the unix epoch to timezone-less date time representation. When the it is passed to `strflocaltime`, it interprets the date and time in the local timezone. So it looks fine to me.

**Comment by pkoppstein** [comment]
@itchyny - I understand your reasoning, but `gmtime` is not supposed to be a "timezone-less data time representation":

> gmtime
struct tm * gmtime (const time_t * timer);
Convert time_t to tm as UTC time
Uses the value pointed by timer to fill a tm structure with the values that represent the corresponding time, expressed as a UTC time (i.e., the time at the GMT timezone).

[https://www.cplusplus.com/reference/ctime/gmtime/]

**Comment by pkoppstein** [comment]
The jq documentation is pretty clear:

> The gmtime builtin consumes a number of seconds since the Unix epoch and outputs a "broken down time" representation of Greenwhich Meridian time

The C/C++ struct likewise does not include an explicit timezone indicator or offset because it always is anchored to UTC.
