### ISSUE TITLE
Negative number modulus *big.Int behaves differently to int

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#117]
```sh
$ go run cmd/gojq/main.go -n '2147483647 as $maxHalfInt | -1 % ($maxHalfInt, $maxHalfInt+1)'
-1
2147483647
```
Im not that familiar with modulus math but the comment for [*big.Int Mod](https://pkg.go.dev/math/big#Int.Mod) might be a clue:
> Mod sets z to the modulus x%y for y != 0 and returns z. If y == 0, a division-by-zero run-time panic occurs. Mod implements Euclidean modulus (unlike Go); see DivMod for more details.

**Comment by itchyny** [comment]
Fixed, thanks.

**Comment by wader** [comment]
👍  thanks for quick fix
