### ISSUE TITLE
[documentation enhancement] key words as $-variables

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#120]
One important improvement that does not seem to be mentioned on the README page is that gojq lifts the jq-imposed restriction that "$-variables" cannot also be jq [keywords](https://github.com/stedolan/jq/wiki/How-to:-Avoid-Pitfalls#keywords).

**Comment by wader** [comment]
Thanks for notice, that explains the `$end` parse error i saw. So it's not considered a bug in jq?

**Comment by pkoppstein** [comment]
As best I can tell, it’s considered an area for improvement :-)

**Comment by itchyny** [comment]
jq allows to use keyword variables but does not support binding.

```
 % jq -nc 'def f($as): $as,[$as,{$as}]; f(.)'
null
[null,{"as":null}]
```

**Comment by itchyny** [comment]
But I'd say I just implemented the lexer as normal without noticing the jq restriction.

**Comment by pkoppstein** [comment]
For reference, the jq restrictions are illustrated by:
```
jq -n '1 as $as | $as'
jq: error: syntax error, unexpected as, expecting IDENT (Unix shell quoting issues?) at <top-level>, line 1:
```
