### ISSUE TITLE
Handling of globs in input files - behaviour difference from jq

### ISSUE THREAD

**Issue by harig** [itchyny/gojq#126]
gojq version : build based on bd475282098d3a ; OS: Win10-64

If  a file path glob is passed as argument for input files to gojq.exe, it is  not handled, a file open error is shown. 
example command line to be used inside a directory with many files starting with the letter 'a'.
`gojq "." a*.json`
`gojq: open a*.json: The filename, directory name, or volume label syntax is incorrect.`

This differs from the behaviour of jq.exe  which reads and processes the matching files.  It would be nice if it were possible to use file paths globs instead of having to specify all the files on the command line (which gojq also handles well) for cases where one has a directory with many files which you want to be slurped and processed.

**Comment by harig** [comment]
Indeed, it works within Msys2's bash. The error appears when gojq is run within cmd.exe.

**Comment by itchyny** [comment]
Expanding filepath wildcards in program is a wrong solution here. I have accepted such changes in another project, but it's a bad idea, wildcard expansion should be handed by shells. I'm sorry for not supporting cmd.exe, but considering the situation Windows devs are moving to WSL, it's unlikely to introduce dirty workaround here.
