### ISSUE TITLE
regex bug: "x" option not handled properly

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#127]
gojq does not handle the "x" option properly. E.g.:
```
def regex:
   "^(?<n>.*?)  \\s+" ;

"Nieuwe gracht 20 zw/4"
| capture(regex;"x")
```

jq output:  {"n":"Nieuwe"}

gojqMaster: (empty)

**Comment by itchyny** [comment]
Ok, it should validate the flags.
