### ISSUE TITLE
Simpler interface for using as library

### ISSUE THREAD

**Issue by fiibbb** [itchyny/gojq#13]
It seem to make sense to expose an interface such as the following:
```
input := []byte("[{"foo":42}, {"foo":43"}]")
query, _ := gojq.Parse(". | map(.foo)")
var output []byte
output, _ = query.Run(input)
fmt.Printf("%v\n", output) // prints `[42, 43]`
```
This would allow user to operate on (valid) json bytes. I looked around the source and seems this is not quite straightforward as of today. Any recommendations?

**Comment by itchyny** [comment]
This is not that simple. This feature leads to various options for output formatting (indentation number, html escape, etc) so I don't like it. Parsing and formatting phases are entrusted to the user.

**Comment by fiibbb** [comment]
Make sense. Thanks.

**Comment by donatj** [comment]
I do wish there were just an easy way to get JSON back out.
