### ISSUE TITLE
Query language documntation

### ISSUE THREAD

**Issue by Xumeiquer** [itchyny/gojq#130]
Is there any place where explains the whole query language for gojq?

**Comment by wader** [comment]
Hi, i think a good place to start is jq's [manual](https://stedolan.github.io/jq/manual/), also jq's wiki has a good page called [jq Language Description](https://github.com/stedolan/jq/wiki/jq-Language-Description) with a more detailed description.

**Comment by Xumeiquer** [comment]
So is this fully compatible with jq?

**Comment by wader** [comment]
Not fully but very close i would say, see https://github.com/itchyny/gojq#difference-to-jq for differences.

**Comment by itchyny** [comment]
Already answered well so closing. These links are good references so firstly learn from them. In the absence of formal language specification for jq language, gojq just tries to implement how jq command works, with some useful extensions and bug fixes. Hopefully someone creates a well-defined language and comprehensive test suites.
