### ISSUE TITLE
Export JSON Colored Printer

### ISSUE THREAD

**Issue by weberc2** [itchyny/gojq#132]
Hello, thanks a ton for this project--I was really happy to hear someone made JQ in pure-Go, and to fix so many other issues on top of that is just incredible (and even more so to expose it all as a library)! That said, I have a use case in which I'd like to be able to output JSON like the `gojq` CLI does--colors when writing to a TTY by default. It seems like this is all private to the `cli` package--would it be possible to make this a public package that one can use when importing the gojq module?

**Comment by itchyny** [comment]
Unlikely to export these functions from this project. The encoder implementation is coupled with the command and hard to expose as library (for example, making the colors configurable is not straight forward). Instead, I recommend using the [`gojq.Marshal`](https://pkg.go.dev/github.com/itchyny/gojq#Marshal) with the [`go-prettyprint`](https://github.com/hokaccha/go-prettyjson/) library. The library automatically detect the TTY output. Here's sample code.

```go
package main

import (
	"fmt"
	"log"
	"math"

	"github.com/fatih/color"
	"github.com/hokaccha/go-prettyjson"
	"github.com/itchyny/gojq"
)

// Same colors with gojq.
var format = &prettyjson.Formatter{
	KeyColor:    color.New(color.FgBlue, color.Bold),
	StringColor: color.New(color.FgGreen),
	BoolColor:   color.New(color.FgYellow),
	NumberColor: color.New(color.FgCyan),
	NullColor:   color.New(color.FgHiBlack),
	Indent:      2,
	Newline:     "\n",
}

func main() {
	// Use gojq.Marshal instead of json.Marshal to handle NaN and Infinities.
	bs, err := gojq.Marshal(map[string]interface{}{
		"x": 1,
		"y": math.NaN(),
		"z": []interface{}{nil, false, true, "abc", math.Inf(0)},
	})
	if err != nil {
		log.Fatal(err)
	}
	bs, err = format.Format(bs)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s\n", bs)
}
```
