### ISSUE TITLE
Issue with path expression caused by NaN != NaN

### ISSUE THREAD

**Issue by MiSawa** [itchyny/gojq#133]
```
gojq -n '[nan] | path(.[0])'
```
should output `[0]` but throws an error. The same code works in `jq`.
I believe we need more sophisticated equality check instead of `reflect.DeepEqual` used for sanity checks on path expansion.

**Comment by itchyny** [comment]
Thanks for reporting, fixed now.

**Comment by MiSawa** [comment]
Awesome, thank you for the swift fix!
