### ISSUE TITLE
discrepancy/bug:  `def f($keys)`

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#135]
It took me a while to figure out why the following program works with jq but fails with gojq, and so I hope that you'll agree that this is a discrepancy that ought to be rectified:

```
for jq in jqMaster gojqMaster
do
  echo $jq ::
  echo '{"name": ["Paul"]}' | $jq -Mc '

  def objectify($keys):
    with_entries( .key = $keys[.key] );

  keys as $keys
  | [.[]]
  | transpose
  | map( objectify($keys) )
' 
done
```

The above produces:
```
jqMaster ::
[{"name":"Paul"}]
gojqMaster ::
gojq: expected an object but got: array (["Paul"])
```

The problem (of course (?)) goes away if one changes the formal argument of the `def` e.g. to $xkeys

**Comment by itchyny** [comment]
Thanks for reporting, fixed.

**Comment by pkoppstein** [comment]
That was quick!  Very impressive.

Thank you.
