### ISSUE TITLE
Empty array flatten regression since "improve flatten performance by reducing copy"

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#141]
gojq master
```
$ go run cmd/gojq/main.go -n '[] | flatten'
null
```
gojq a1a2550d771e1937df72b4df4fcb729af615090f~1
```
$ go run cmd/gojq/main.go -n '[] | flatten'
[]
```

I think the problem is that the new version ends up doing `[] | add` for `[]` input. Just add a special case or is there some neater way?

**Comment by itchyny** [comment]
Thanks for catch.

**Comment by wader** [comment]
👍
