### ISSUE TITLE
--arg=key=val: unexpected token "="

### ISSUE THREAD

**Issue by fugkco** [itchyny/gojq#143]
Seems the usage of the `gojq` doesn't match the behaviour. When you do `--arg=key=val` it fails to parse the values:

```
$ gojq -n --arg=key=val '{"hello": $key}'
gojq: invalid query: --arg=key=val
    --arg=key=val
             ^  unexpected token "="
```

The help function shows the following:
```
$ gojq --help
...
      --arg=               set variable to string value
...
```

The actual behaviour somewhat matches `jq` itself:

```
$ jq -n --arg=key=val '{"hello": $key}'
jq: Unknown option --arg=key=val
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```

Which matches `jq`'s help:

```
$ jq --help
...
  --arg a v        set variable $a to value <v>;
...
```

I guess I'm not expecting `--arg=var=value` to work, more so that the help should reflect what's expected. It took me a while to realise that the help doesn't match reality. I presume this is the same for `--argjson`, `--slurpfile`, and `--rawfile`.

**Comment by itchyny** [comment]
Fixed.
