### ISSUE TITLE
[feature request] can cli.Run provide CompilierOption args  so user can override?

### ISSUE THREAD

**Issue by darren** [itchyny/gojq#145]
by adding a variadic args:
https://github.com/itchyny/gojq/blob/27d17e55f431c0308e3f890b050d66c27d7338fc/cli/run.go#L6
```go
// Run gojq.
func Run(opts ...gojq.CompilerOption) int {
	return (&cli{
		inStream:  os.Stdin,
		outStream: os.Stdout,
		errStream: os.Stderr,
		options:   opts,
	}).run(os.Args[1:])
}
```

so user can call with somethings like this:
```go
opts :=  []gojq.CompilerOption{
    gojq.WithFunction("func1", 0, 0, func1),
    gojq.WithFunction("func1", 0, 0, func2),
}
cli.Run(opts...)
```

**Comment by itchyny** [comment]
The cli package is implemented for the gojq command itself so I don't want to put effort to make it extensible by users. The compiler option is just a side of the command so accepting this idea leads to bunch of options to overwrite the behavior of cli. Adding a new function by Go is understandable wish but needs much more research for better solutions like RPC (but I don't have time and motivation to think about this). In the meanwhile forking would be simpler solution.
