### ISSUE TITLE
bug: submodules / hierarchical namespaces

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#146]
```
$ jq -n 'def a::b::c: "abc"; a::b::c'
"abc"

$ gojqMaster -n 'def a::b::c: "abc"; a::b::c'
gojq: invalid query: def a::b::c: "abc"; a::b::c
    def a::b::c: "abc"; a::b::c
        ^  unexpected token "a::b"

$ gojqMaster --version
gojq 0.12.5 (rev: 27d17e5/go1.17)
```

**Comment by itchyny** [comment]
Wait, is this an official feature of jq? I can't find any document on this.

**Comment by pkoppstein** [comment]
It's true - the official documentation is much too sparse,  and I could have given a more definitive example, but the key principle is stated in the "man" page:

> The module's symbols are prefixed with "NAME::".

The module system for jq was assembled rather hastily in my opinion, but the key idea (for better or worse) was to base it on namespaces.  It's for that reason that you can use `foo::bar` outside of a declared module, and ditto for `foo1::foo2::bar` etc.  

If you want to design a different module system for jq, I'd just ask that you ensure it supports hierarchical modules.

**Comment by itchyny** [comment]
Hmm, from the manual I can only see the intention that the single depth identifier prefix is given by the module user. So in my understanding, a jq module does not have a namespace, and defining filters with a prefix in modules will duplicate the identifier prefixes for module users. Looking through the thread, the identifier prefix is only intended for invocation, and the real lexer change unintentionally extend the syntax of declaration identifiers. Changing gojq lexer and parser is straightforward, but I still need to know how _hierarchical namespaces_ are useful in real cases (Using namespace in command line query is for simplified example isn't it).

**Comment by pkoppstein** [comment]
As I already implicitly pointed out, hierarchical namespaces are implied by the ability to import modules that import modules.

**Comment by itchyny** [comment]
It is unlikely to implement in the near future so closing. If this use case is more common and has more users I'll reconsider.
