### ISSUE TITLE
Support for types in YAML

### ISSUE THREAD

**Issue by chitoku-k** [itchyny/gojq#147]
gojq accepts YAML input by `--yaml-input` but it doesn't correctly handle types in YAML:

```console
$ gojq --yaml-input <<< 'on: on'
{
  "on": "on"
}

$ gojq --yaml-input --yaml-output <<< 'on: on'
"on": "on"
```

As per JSON spec, it sounds reasonable that gojq emits string keys, but the value part should at least be a boolean.

FYI, the following is how it works in the other implementation.

```console
$ irb
irb(main):001:0> require 'yaml'
=> true
irb(main):002:0" YAML.load(<<EOF)
irb(main):003:0" on: on
irb(main):004:0> EOF
=> {true=>true}
```

Thanks in advance.

**Comment by itchyny** [comment]
The yaml library gojq uses defaults to the behavior of YAML 1.2. There is no plan to support legacy standard.

**Comment by chitoku-k** [comment]
Thanks for answering! I wonder it could be better documented but anyway I am closing this issue.
