### ISSUE TITLE
documentation: leading 0s

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#150]
jq and gojq handle leading 0s differently.  Has this been documented?

```
$ gojq  . <<< 0862
0
862

$ jq  . <<< 0862
jq  . <<< 0862
862
$
```

**Comment by itchyny** [comment]
This is considered as the instance of difference on the JSON parser strictness. I don't like the jq behavior handles invalid JSONs.

**Comment by pkoppstein** [comment]
Is gojq's internal inconsistency noted?

**Comment by itchyny** [comment]
There is no inconsistency because jq query and JSON have different syntax.
