### ISSUE TITLE
Cannot get gojq

### ISSUE THREAD

**Issue by chippyash** [itchyny/gojq#151]
go get github.com/itchyny/gojq/cmd/gojq
go: found github.com/itchyny/gojq/cmd/gojq in github.com/itchyny/gojq v0.12.6
# github.com/itchyny/gojq
/home/foo/go/pkg/mod/github.com/itchyny/gojq@v0.12.6/module_loader.go:37:15: undefined: os.ReadFile
/home/foo/go/pkg/mod/github.com/itchyny/gojq@v0.12.6/module_loader.go:55:14: undefined: os.ReadFile
/home/foo/go/pkg/mod/github.com/itchyny/gojq@v0.12.6/module_loader.go:88:15: undefined: io.ReadAll

Any ideas?
Go is such a muppet when it comes to dependencies!

Any help considered.
Thanks

**Comment by itchyny** [comment]
Use Go v1.16 or later. Due to the [Release Policy](https://go.dev/doc/devel/release), Go supports only two newer major releases. Currently v1.16 and v1.17 are supported.
