### ISSUE TITLE
how tou count output ? 

### ISSUE THREAD

**Issue by leiyang** [itchyny/gojq#152]
'. |select(.name=="aaa")' , how to count  this ?

**Comment by wader** [comment]
This is more a question for stackoverflow i think but you probably want to somehow iterate the input, surround your filter expression with `[...]` to collect and use `length` to get the count. Something like this:
```
$ echo '[{"name": "aaa"}, {"name": "aaa"}]' | jq '[.[] | select(.name=="aaa")] | length'
2
```

**Comment by leiyang** [comment]
I had found the answer, the same as yours , thanks, I need to learn more about jq
