### ISSUE TITLE
Feature Request: Yaml input and output

### ISSUE THREAD

**Issue by awilcots** [itchyny/gojq#155]
My apologies if this is not formatted as an issue here should be. Please let me know if this should be reformatted. 

A flag like `--yaml-through` to denote both `--yaml-input` and `--yaml-output` flags. This may fall under a QoL request, but I think it'd be a nice to have feature.

**Comment by itchyny** [comment]
It is messy to add a flag combining multiple flags and this is unlikely to be implemented. You can define function in your shell config.
```sh
gojq-yaml() {
  gojq --yaml-input --yaml-output "$@"
}
```
