### ISSUE TITLE
flag for compile or env for yaml input default

### ISSUE THREAD

**Issue by proceau** [itchyny/gojq#159]
Hi,

it's possible to add flag in compilation or env variable for enable yaml-input by default ?

because yaml spec 1.2.2 accept yaml & json without any problem, and for me --yaml-input it's useless, because json  it's valid yaml in 1.2.2 spec

**Comment by itchyny** [comment]
You can define function in your shell config to always enable the command line flag.
```sh
gojq() {
  command gojq --yaml-input "$@"
}
```
Changing the behavior due to some environment variable is dangerous so unacceptable.

**Comment by proceau** [comment]
thank for example
but need after that --json-input :p
it's possible ?

**Comment by itchyny** [comment]
Check each values in `$@` and omit `--yaml-input` when you find `--json-input`.
```zsh
gojq() {
  local yaml="--yaml-input"
  local arg
  for arg in "$@"; do
    if [[ "$arg" = "--json-input" ]]; then
      unset yaml
    fi
  done
  command gojq ${yaml:+"$yaml"} "${@:#--json-input}"
}
```

**Comment by proceau** [comment]
\ wow /
a big thank-you
