### ISSUE TITLE
Using cli functionality in the code

### ISSUE THREAD

**Issue by IvanKalimanov** [itchyny/gojq#161]
Hi!
Are there any ways to use cli functionality like `--raw-input --slurp` while using `gojq` as a library? 
I have to send request to Gitlab API in order to validate generated gitlab-ci file. In the [documentation](https://docs.gitlab.com/ee/api/lint.html#use-jq-to-create-and-process-yaml--json-payloads) said that this yml file should be escaped and encoded to JSON. This can be done by `jq --raw-input --slurp < test.yml`. `gojq` gives same results and that is perfect, but I need this functionality in my code. 
Thank you!

**Comment by itchyny** [comment]
You don't need to use gojq in the use case. Just [`os.ReadFile`](https://pkg.go.dev/os#ReadFile) to read the file content and [`json.Marshal`](https://pkg.go.dev/encoding/json#Marshal) to encode. This is much simpler than adding gojq dependency, and also reduces the binary size much.

**Comment by IvanKalimanov** [comment]
Thank you very much!
