### ISSUE TITLE
Add support for producing LD-JSON output

### ISSUE THREAD

**Issue by ahochsteger** [itchyny/gojq#162]
Currently it is possible to consume line-delimited JSON data and it would be great to support producing it as output too.

**Comment by itchyny** [comment]
The jq and gojq can output multiple JSONs, like `jq -n "{x: range(3)}"`. Is that what you want?

**Comment by ahochsteger** [comment]
@itchyny this sort of wurks, but the output is not formatted as line-delimited json, having only one line per JSON object.

I was able to find a workaround though, but I am not sure if this is guaranteed to never put a linefeed inside the JSON object:
```bash
$ echo '[{"a":1,"b":{"c":2}},{"a":3,"b":{"c":4}}]' | gojq -c '.[]'
{"a":1,"b":{"c":2}}
{"a":3,"b":{"c":4}}
```
If this can be guaranteed, than maybe it's just a matter of documentation or improvement of the help message for the option "-c".

**Comment by itchyny** [comment]
Yes, that compact output option works for your use case. The [jq Manual](https://stedolan.github.io/jq/manual/) mentions this option as `Using this option will result in more compact output by instead putting each JSON object on a single line.`.
