### ISSUE TITLE
Multiplication regression since "detect overflow in each operator implementations"

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#169]
Hello, i noticed this while working on the fq fork. Haven't dug much deeper into it yet, guess it's because of `l * r` overflow to zero and the `v == 0` check?

gojq master:
```
$ go run cmd/gojq/main.go -n '4611686018427387904*4'
0
```

gojq 9d980bc~1:
```
$ go run cmd/gojq/main.go -n '4611686018427387904*4'
18446744073709551616
```

**Comment by itchyny** [comment]
Fixed, thanks.
