### ISSUE TITLE
Could `mktime` have sub-second resolution?

### ISSUE THREAD

**Issue by amesgen** [itchyny/gojq#171]
Consider
```shell
 $ echo '"2022-04-12T14:34:13.55Z"' | gojq 'strptime("%Y-%m-%dT%H:%M:%S.%fZ") | mktime'
1649774053
```
I think it would be useful if this could return `1649774053.55` (or if there was an alternative to `mktime` which did). It can be emulated with
```shell
 $ echo '"2022-04-12T14:34:13.55Z"' | gojq 'strptime("%Y-%m-%dT%H:%M:%S.%fZ") | (mktime + .[5] - (.[5] | floor))'
1649774053.55
```
which is a bit convoluted.

**Comment by itchyny** [comment]
This is already supported in the HEAD version.

**Comment by amesgen** [comment]
Excellent, thanks, closing then!
