### ISSUE TITLE
Export gojq.typeErrorPreview and possibly some error types

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#174]
Hi, the `gojq.typeErrorPreview` function and possibly some of the `expected*` error types would be very useful for custom function to produce good error messages. Currently in fq i've copied parts of error.go to use them. Have had a plan for while to instead exporting some of them in the gojq fq fork instead but thought i should ask if you would consider exporter some in gojq instead?

**Comment by wader** [comment]
Also if this kind of functionality is useful to provide we should maybe think a bit about the API and naming? maybe preview should be part of the encoder.go code/API etc?

**Comment by itchyny** [comment]
Exporting error types mess the library API, and they are easy to implement so that would unlikely to happen. The previewing utility is the exception, and looks useful actually (for saving memory allocation compared to `gojq.Marshal`). There're various concerns though, about naming and max width. I need to be quite careful for naming, and I don't want to expose it until come up with good name.

**Comment by wader** [comment]
Ok very understandable and just preview or an encoder with limit support would be great. Maybe the std `encoding/*` packages can give some API inspiration? `NewEncoder` with a truncate setter method? or maybe `NewLimitedEncoder`?

Maybe the encoder in `encoder.go` and `cli/encoder.go` could be unified somehow? but i guess there is a good reason why they separate right now, different needs and messy to combine?

**Comment by itchyny** [comment]
While gojq has already exposed Marshal, having full functionality like std encoding packages does not suit for the purpose of this library. I'd hesitate even to expose the encoder. Also, I'm afraid that marshalization with hard limit width does not exist in std libraries (I think this is the Go way; appending byte buffer grows automatically). By the way, `go:linkname` would help you in the meanwhile.
```go
package main

import (
	"fmt"
	_ "unsafe"

	_ "github.com/itchyny/gojq"
)

//go:linkname preview github.com/itchyny/gojq.preview
func preview(interface{}) string

func main() {
	fmt.Println(preview(
		[]interface{}{nil, false, true, 0, 1, 2, 3, 4, 5, 6, 7},
	))
}
```

**Comment by wader** [comment]
Ok thanks, no worries. Maybe i will do an attempt at an encoder or marshal API in the fq fork, can let you know if i come up something resonable.

Thanks for the link trick, i've used it with cgo but didn't know it could be used like that.

**Comment by itchyny** [comment]
After consideration on this issue for a few days, I have exported two functions for this purpose, `gojq.TypeOf` and `gojq.Preview`. I don't want to bring this library a kind of full encoder APIs for general purpose, but I concluded it is worth exporting previewing utilities for the same purpose as used internally for built-in functions. You can use like `TypeOf(v) + " (" + Preview(v) + ")"`.

**Comment by wader** [comment]
@itchyny Thanks, is a good compromise i think
