### ISSUE TITLE
How to write a function that returns empty?

### ISSUE THREAD

**Issue by xguo-prestolabs** [itchyny/gojq#180]
I'm trying to use gojq as a library. I need to add a function using WithFunction, 
so that it return emtpy for certain input.  How can I achieve that?

**Comment by itchyny** [comment]
Use [gojq.WithIterFunction](https://pkg.go.dev/github.com/itchyny/gojq#WithIterFunction) and return [gojq.NewIter()](https://pkg.go.dev/github.com/itchyny/gojq#NewIter).

**Comment by xguo-prestolabs** [comment]
thanks, let me try

**Comment by xguo-prestolabs** [comment]
works perfectly
