### ISSUE TITLE
Ability to marshal bytecode to protobuf

### ISSUE THREAD

**Issue by xakepp35** [itchyny/gojq#187]
Greetings, comrade! This is a big feature request and improvement direction hint, if you afford :)

We have a big cloud project, which uses jq as a query language for data. It would be benefittial to have an ability to be able to marshal compiled RPN VM bytecode to a protobuf binary format, in order to send a query to multiple machines for parallel execution on a bigdata, or embed it as a part of bigger inner-level requests (compile once-execute multiple) - it would make it really optimized and production-grade project..

**Comment by xakepp35** [comment]
PS. I know, - it will require a big remake. couple of key remarks:
1) proto does not allow free use of interface{} - you can use oneof (better for opcodes) / anypb.Any (fast replacement of interfaces) 
2) you cannot store closures - they cant be sent over network - linker issue

**Comment by itchyny** [comment]
I can't understand the benefit of byte code over sending jq query by string, which is more stable and reliable way, and much unlikely to break between different library versions. Also, byte code will be a larger data to send through network. Compiler of the gojq is quick enough and I don't think we can make a stable spec for the compiled code.
