### ISSUE TITLE
How to pass array to `query.Run`

### ISSUE THREAD

**Issue by asaf** [itchyny/gojq#19]
Hey,

I have an array in the form of `[]map[string]interface{}`

I would like to run a query such `.[] | .id` but it fails with:

```
expected an object but got: array ([{"id":"fb4ae77f-144d- ...)
```

what should I pass to `query.Run` in order to execute gojq over an array ?

Thanks

**Comment by itchyny** [comment]
Please pass `[]interface{}` for array and `map[string]interface{}` for map.

**Comment by asaf** [comment]
@itchyny thanks! keep the hard work, the project is great.
