### ISSUE TITLE
go(jq) incompatibility with the --sort-keys & --unbuffered command line options

### ISSUE THREAD

**Issue by yertto** [itchyny/gojq#190]
Regarding https://github.com/itchyny/gojq#difference-to-jq
> gojq does not support some functions intentionally; ...  `--sort-keys`, `-S` (sorts by default because `map[string]interface{}` does not keep the order), `--unbuffered` (unbuffered by default)

The fact that the `--unbuffered` & `--sort-keys` are both *off* by default in `jq` and *on* by default in `gojq`, presents an incompatibility with `jq`.

The README is being used to communicate this difference, however perhaps that could be done by printing an incompatibility warning to stderr when the options aren't present.

So, if `gojq` chose to accept these options (without actually doing anything with them), they wouldn't have any effect on the invocation other than silencing the incompatibility warnings, but it would then facilitate `gojq` to be a drop-in replacement for `jq` for scripts that actually want to _use_ those features...

Here's a simplified example script `a.sh` written to work with both `jq` *and* `gojq` depending on whichever `JQ` the user wants to use:
```sh
#!/bin/sh
JQ=${JQ:-jq}

echo "Look at the (sorted) pretty JSON:"
$JQ --sort-keys

echo "That was as (unbuffered) easy as"
echo '1 2 3' |
  $JQ --unbuffered
```

And that script can be run with `jq`:
`a.sh <<< '{"b": 2, "a": 1}'`
```
Look at the (sorted) pretty JSON:
{
  "a": 1,
  "b": 2
}
That was as (unbuffered) easy as
1
2
3
```

But currently throws these annoying and unnecessary errors when run with `gojq`:
`JQ=gojq a.sh <<< '{"b": 2, "a": 1}'`
```
Look at the (sorted) pretty JSON:
gojq: unknown flag `--sort-keys'
That was as (unbuffered) easy as
gojq: unknown flag `--unbuffered'
```

So, would there be any downside in allowing `gojq` to just silently accept these "defaulted" flags in order to maintain this command line option compatibility with `jq`?

ie. to avoid many snippets of code like this appearing in shell scripts at all the incompatible jq invocation points:
```sh
#!/bin/sh
JQ=${JQ:-jq}

echo "Look at the (sorted) pretty JSON:"
if [ "$JQ" = "gojq" ]; then
  $JQ
else
  $JQ --sort-keys
fi

echo "That was as (unbuffered) easy as"
echo '1 2 3' |
  if [ "$JQ" = "gojq" ]; then
    $JQ
  else
    $JQ --unbuffered
  fi
```

**Comment by itchyny** [comment]
I think the following one-liner snippet is enough to make all `$JQ` work in compatible way between `JQ=jq` (or absence) and `JQ=gojq`. This one-liner would reduce mistakes to forget `--sort-keys` and introduce incompatible behavior on adding some code to that script. It needs more time for me to judge it's ok to add no-op flags or not.
```sh
test "$JQ" = jq && jq() { command jq --sort-keys --unbuffered "$@"; }
```

**Comment by yertto** [comment]
Yer @itchyny,  if all the folks like me wanting to support both implementations put that one liner in all our scripts, then yer - I think it'd work, but IMO an incompatibility warning when they're not present, *would* be better than having to discover that fact in a README or wiki.
(And perhaps a `GOJQ_SILENCE_INCOMPATIBILITY_WARNINGS=true` would be good so folks can turn them off.)

>  It needs more time for me to judge it's ok to add no-op flags or not.
Yer - definitely - take your time. 🙏

Perhaps it'd help if you tried re-framing your perspective on the issue though...

If it *was* simple to implement unsorted keys in `gojq`, would sorted keys *still* be your preferred default for `gojq`?
And further to that, would you then try persuading the `jq` maintainers to flip their default to use sorted keys as well?

**Comment by itchyny** [comment]
I'm still in doubt that allowing script users to chose the jq program is a good idea. I'm grad to see many people install gojq and alias it to jq in shell configurations. In daily terminal operations, the features of gojq (like error messages) bring us better life (I hope), but why do you need to allow shell script users to choose the jq program? jq is still available in many platform, and just using jq (not $JQ) in scripts erases various concerns away.

**Comment by yertto** [comment]
> I'm still in doubt that allowing script users to chose the jq program is a good idea

I've ended up here from discovering that `gojq` is a better & faster command line version of `jq` that users of my `jq` programs (written using [jq-sh](https://github.com/jq-sh/jq-sh)) might chose to plug in as a replacement for `jq` to get better performance.

Although I'd still very much like my programs to maintain their backwards compatibility with `jq`, so they can continue to run in the tight server/spaces where only `jq` exists, as much like `grep` & `sed` - it's pretty much guaranteed to be there these days.
(ie. one of the reasons why I was drawn to `jq` in the first place).

But yer, is it a _"good idea to give script users this choice"_?
I don't know - maybe, maybe not.
However since `gojq` is *so* close to being compatible with `jq`, why not?
(ie. by - amongst other things - choosing to stay aligned with `jq`'s defaults wherever possible.) 

> just using jq (not $JQ) in scripts erases various concerns away.

True, that jq function `jq() { command jq --sort-keys --unbuffered "$@"; }` would bring `jq` in alignment with the opinions of `gojq` regarding the default behaviour of these two `jq` features.

However, it backs us into a corner if the alternative to the defaults are ever desired in `jq()`, or ever implemented in `gojq`.
1. `sort-keys`
  It could be argued that JSON keys should *never* be relied on to be sorted, so they may as well *always*  be sorted, without any option to ever maintain their order.
  And perhaps `keys_unsorted` should be removed from `jq` as just a "bad idea".
  However now, not only has `gojq` got a different opinion on the default, it would now be imposing this opposing default on to `jq` when using the `jq()` function.
  And what happens if `gojq` ever does chose to implement `keys_unsorted`?
  (ie. if Go's standard library ever does)
  Would `gojq` then facilitate this new feature with a `--dont-sort-keys` option, or would it then flip the default around to realign with `jq`?

2. `unbuffered`
  Similarly, what happens if `gojq` ever wants to facilitate buffered input?
  Would `gojq` do this with a `--buffered` option, or would it flip the default around to realign with `jq`?

**Comment by itchyny** [comment]
Speaking of the default behavior of gojq, I would implement these flags if possible, to make gojq more closer to jq. So when it is ready to implement unordered map handling, I will bump the (maybe major) version and change the default behavior (but unordered map support would not be implemented in the near future considering the absence of standard way or handling unordered map in Go). I don't think changing the behavior of jq is a good idea.

**Comment by yertto** [comment]
Sounds like a plan.
Thanks for hearing the issue out, but mostly thanks for such a great tool.
Closing.
