### ISSUE TITLE
How to pass CLI flags (null-input) when using gojq as package

### ISSUE THREAD

**Issue by brunetto** [itchyny/gojq#193]
Hi, 
I need to pass the `--null-input` flag in order to have my jq query working in my project. 
Is there a way to pass this option to gojq if I'm using it importing the package, not in the CLI?
I can't find any example or information and looking at the cli implementation I didn't find an answer either.

Thanks

**Comment by wader** [comment]
If you'r using the gojq package to compile/run yourself i think null input should be more or less just to pass nil as input to `Run`.
```go
q, err := gojq.Parse("...")

iter := q.Run(nil)
...

// or
c, err := gojq.Compile(q)
iter := c.Run(nil)
...
```
For examples maybe see https://pkg.go.dev/github.com/itchyny/gojq#example-Code.Run or examples in https://github.com/itchyny/gojq/blob/main/query_test.go

**Comment by brunetto** [comment]
Hi, thanks for your answer.
I'll try to explain my issue al little better!

The code to illustrate this is the following:

```go
package main

import (
	"errors"
	"fmt"
	"log"

	"github.com/itchyny/gojq"
)

func main() {
	q, err := gojq.Parse(query)
	dieIf(err)

	code, err := gojq.Compile(q)
	dieIf(err)

	iter := code.Run(input())

	res, ok := iter.Next()
	if !ok {
		dieIf(errors.New("not ok"))
	}

	if err, ok := res.(error); ok {
		dieIf(err)
	}

	fmt.Println(res)
        // 2022/10/12 09:55:38 not ok
        // exit status 1
}

func dieIf(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func input() any {
	input := map[string]any{
		"key1": []any{map[string]any{"lang": "en", "value": "val1"}},
		"key2": []any{
			map[string]any{
				"boolean": map[string]any{"key": "boolean_false", "value": false},
			},
		}}

	return input
}

// {
//      "key1": [{"lang": "en", "value": "val1"}],
//      "key2": [
// 		   	{"boolean": {"key": "boolean_false", "value": false}}
//      ]
// }

// the query is a little bit complex because of the original json data

var query = `
walk
(if (type=="array") then 
	del(.[] | select
		(type=="object" and 
			(
				(.lang != null and .lang != "it") 
			)
		)
	) else . end 
) | 
{
    "0": (try (.key1[].value) catch null | (if . == false then "false" else . end) ? // "")
    ,"1": (try (.metadata[] | select(.[].key == "boolean_false")[]? | .value) catch null | (if . == false then "false" else . end) ? // "")
}
`

```

The corresponding jqPlay snippet are:
* working https://jqplay.org/s/2U7_8QgcaW3
* not working https://jqplay.org/s/efTQzyWjwVv

the difference being the "Null Input" flag.
I need to have the equivalent of the "thick" on the "Null Input" box in jqPlay but in the code, while keeping query and input the same.

Thank

**Comment by wader** [comment]
Hi again, i wonder if it has to do more with the query than null input.

Ex using gojq CLI:

```sh
# with JSON input
$ echo '{"key1":[{"lang":"en","value":"val1"}],"key2":[{"boolean":{"key":"boolean_false","value":false}}]}' | gojq 'walk(if (type == "array") then del(.[] | select(type == "object" and ((.lang != null and .lang != "it")))) else . end) | { "0": (try (.key1[].value) catch null | (if . == false then "false" else . end)? // ""), "1": (try (.metadata[] | select(.[].key == "boolean_false")[]? | .value) catch null | (if . == false then "false" else . end)? // "") }'
<no output>

# with JSON input but prepend query with 'input | ...'
$ echo '{"key1":[{"lang":"en","value":"val1"}],"key2":[{"boolean":{"key":"boolean_false","value":false}}]}' | gojq 'null | walk(if (type == "array") then del(.[] | select(type == "object" and ((.lang != null and .lang != "it")))) else . end) | { "0": (try (.key1[].value) catch null | (if . == false then "false" else . end)? // ""), "1": (try (.metadata[] | select(.[].key == "boolean_false")[]? | .value) catch null | (if . == false then "false" else . end)? // "") }'
{
  "0": "",
  "1": ""
}

# null input
$ gojq -n 'walk(if (type == "array") then del(.[] | select(type == "object" and ((.lang != null and .lang != "it")))) else . end) | { "0": (try (.key1[].value) catch null | (if . == false then "false" else . end)? // ""), "1": (try (.metadata[] | select(.[].key == "boolean_false")[]? | .value) catch null | (if . == false then "false" else . end)? // "") }'
{
  "0": "",
  "1": ""
}
```

If you change `input()` to return `nil` https://go.dev/play/p/KOpcjEirqa2 it returns `map[0: 1:]`.

Hope that helps

**Comment by brunetto** [comment]
Ah ok, maybe I spotted the problem in my question: the correct answer I'm looking for is

```
{
    "0":"",
    "1":false
}
```

but I forgot a wrong key in the query: `metadata` should be `key2`.

This should be the correct example: https://go.dev/play/p/csY1ZQnd0Gl.

**Comment by wader** [comment]
Sorry don't really follow what the query is doing but i can see why you probably get zero outputs. After the walk `.key1` end up being '[]' and then `.key1[].value` will return no outputs which i guess you try to fix with `//`? but you probably needs a parentheses to do that, ex `((try (.key1[].value) catch null | (if . == false then "false" else . end) ?) // "")` otherwise the value for the key will end up empty which in return will make the whole object construction end up as empty.

**Comment by brunetto** [comment]
Wow, thank you, this seems to work!!
I didn't thought about parenthesis in that positions and I misunderstood the meaning of null input flag.

Thank you very much!!

**Comment by wader** [comment]
Great! no problem 👍
