### ISSUE TITLE
Array slice difference to jq when using non-integer indexes

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#194]
Accidentally found this difference. Seems like jq floors start and ceils stop index. gojq floors both.

```sh
# version 728837713fb78c6ab6d83180e0c7659693f84d25
$ gojq -n '[0,1,2,3][1.9:2.9]'
[
  1
]

# version jq-1.6-159-gcff5336
$ jq -n '[0,1,2,3][1.9:2.9]'
[
  1,
  2
]
```

**Comment by itchyny** [comment]
The behavior of gojq looks more consistent and well-defined; filtering by `start <= index < end`.

**Comment by itchyny** [comment]
I also noticed the difference of indexing but not sure I should fix this; maybe I'll just add notes on this topic to README.md.

**Comment by wader** [comment]
👍 yeap just document sounds fine

**Comment by itchyny** [comment]
Hmm, my comments `start <= index < end` is incorrect. gojq just truncates down both ends. So `.[1.5:2.5][]` is `.[1:2][]`, not `.[2]` (1.5 <= 2 < 2.5). But I still believe this behavior is pretty common, like `Array.prototype.slice` in JavaScript.

**Comment by itchyny** [comment]
> jq implementation of jq

Aha, that's crazy project 😎.

**Comment by wader** [comment]
😄 kind of useless but have been a very efficient way of learning about jq and parsing :) I was experimenting a bit with writing decoders in jq for fq, something like `decode({a: u3, b: u5, c: utf8(10)})`, which involves some AST-rewriting, which looked a bit like an interpreter :)

**Comment by wader** [comment]
And feel free to help out! there is plenty of ugly and missing things. Have some vague goal of running jqjq with jqjq
