### ISSUE TITLE
Difference between these two functions

### ISSUE THREAD

**Issue by amlwwalker** [itchyny/gojq#197]
I have these two functions, the first one is meant to be "slurping" data.

```go
func ParseLines(rule string, content []interface{}) (string, error) {
	query, err := gojq.Parse(rule)
	if err != nil {
		return "", err
	}
	iter := query.Run(content) // or query.RunWithContext
	var result string
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			fmt.Println(err)
			continue
		}

		if b, err := gojq.Marshal(v); err != nil {
			fmt.Print("could not unmarshal slurpped data ", err)
		} else {
			result += string(b) + "\n"
		}
	}
	return result, err
}
func ParseLinesAlternative(rule string, content []interface{}) (string, error) {
	query, err := gojq.Parse(rule)
	if err != nil {
		return "", err
	}
	iter := query.Run(content)
	v, _ := iter.Next()
	if err, ok := v.(error); ok {
		return "", err
	}
	b, err := gojq.Marshal(v)
	return string(b), err
}
```
For 99% of my usecases the first one works great, but for one usecase the incoming data is massive (60MB text file). If I run that through the first function, it hangs for what seems like forever - i.e I can't wait that long (its for integration tests). It works great when I use the second function.

The jq rule I am using is `'sort_by(.supplement.headers."imp-id") | .[] | del(.supplement.version) | del(."unix-ns") | del(."pred-id") | del(.supplement.data) | del(.supplement.features) | del(.supplement."api-version") | .supplement.headers |= (to_entries | sort_by(.key) | from_entries) | .supplement.blacklists |= (to_entries | sort_by(.key) |from_entries)'`

However in my other cases, which all work great with the first function, if I try to use the second function, I get `expected an object but got: array (...)`. In. this case the rule might be something like
`'{ cid: .["client-id"], hcid: .supplement.headers["client-id"], prod: .supplement.headers.product, cv: .supplement.model.version, mv: .["model-version"], t: .supplement.model.threshold, i: .supplement.model.index }'`

I would like to run them al through the second one as its not looping, which is what I believe is causing the first one to hang (taking a long time to process the data) however I am not sure why the second one gets an array and the first one get an object.

One option is for the very large test/use case I call the second one, but I would like a bit better understanding to the difference here incase its possible that both of these cases could use the second version?

Thanks

**Comment by wader** [comment]
Hi, try replace `result += string(b) + "\n"` (probably causes exponential time as allocates and copies) with a `strings.Builder`. For the jq error i get a feeling you would like to wrap the query in a `map(...)` etc?

**Comment by amlwwalker** [comment]
ahh let me try that, do you mean wrap `'{ cid: .["client-id"], hcid: .supplement.headers["client-id"], prod: .supplement.headers.product, cv: .supplement.model.version, mv: .["model-version"], t: .supplement.model.threshold, i: .supplement.model.index }'` 
in a Go map?
just so i understand what you're suggesting with the map here?

**Comment by wader** [comment]
Nope, wrap the query, something like `map({ cid: .["client-id"], hcid: .supplement.headers["client-id"], prod: .supplement.headers.product, cv: .supplement.model.version, mv: .["model-version"], t: .supplement.model.threshold, i: .supplement.model.index })` but i'm mostly guessing :)
