### ISSUE TITLE
path(getpath()) roundtrip doesn't work for array iterators - .[]

### ISSUE THREAD

**Issue by mruzicka** [itchyny/gojq#198]
### Steps to reproduce:
Try the following expression:
```
path(getpath([["a"], ["b"]][]))
```
against the following input:
```json
null
```

### Expected result:
```json
[
  "a"
]
[
  "b"
]
```
Note that the original `jq` command produces exactly this result.

### Actual result:
```
gojq: invalid path on iterating against: array ([["a"],["b"]])
```

### Additional info:
1. No error is reported when only the `getpath([["a"], ["b"]][])` expression is used. The produced output is the expected one too:
    ```json
    null
    null
    ```
    So, it seems, it is only the combination of `path(getpath())` and the iterator, which causes problems.
2. The problem can be worked around by defining a variable for the iterator as follows:
    ```
    path([["a"], ["b"]][] as $var | getpath($var))
    ````

**Comment by itchyny** [comment]
Thanks for reporting, I'll look into this issue later. In the meanwhile, `path(getpath(["a"], ["b"]))` works as you intended.

**Comment by mruzicka** [comment]
Thanks for looking into this.
I used `[["a"], ["b"]][]` to make the repro code as simple as possible, in my real use case I get the array through a `... | keys` pipeline, which can't be simplified (or at least I don't know how) in the same way as in the repro example.

**Comment by itchyny** [comment]
Another example: `path(getpath([[0]][0]))`.
