### ISSUE TITLE
Raw output

### ISSUE THREAD

**Issue by amlwwalker** [itchyny/gojq#199]
I notice there is a flag that has been merged from a [PR](https://github.com/itchyny/gojq/pull/1) to allow the client to output raw content, I am wondering how to do this using the package programatically.?

What is the mechanism to get the output as "raw" or is this something that is expected to just do manually (by stripping quotes for instance?)

**Comment by itchyny** [comment]
You can implement the behavior by checking the type of result values, and just print it if it is a string.
