### ISSUE TITLE
format strings

### ISSUE THREAD

**Issue by itchyny** [itchyny/gojq#2]
`@csv`, `@json` etc

**Comment by SantoshSrinivas79** [comment]
The performance of `gojq` is quite good and better than `jq`. I'm trying to benchmark performance in couple of scenarios.
Is there an equivalent to the `@csv` option available in `jq`

Also, I tried `gojq` on a very huge json file and it breaks due to a memory error. However, `jq` is able to handle huge files  without issues.

**Comment by itchyny** [comment]
I implemented all the format strings.

**Comment by SantoshSrinivas79** [comment]
@itchyny thank you very much!

Would you be able to make a release. I tried to build from source but I'm getting the below error. I am not familiar with `go`

![Screenshot 2020-01-06 at 10 12 44 AM](https://user-images.githubusercontent.com/1036163/71795654-424afa80-306d-11ea-8043-62a9ab0c983c.png)

**Comment by itchyny** [comment]
@SantoshSrinivas79  Which version of go do you use? `go version`

**Comment by SantoshSrinivas79** [comment]
`go version go1.8.3 darwin/amd64`

**Comment by itchyny** [comment]
@SantoshSrinivas79 That's too old. Please use go 1.13.x.

**Comment by SantoshSrinivas79** [comment]
@itchyny sorry! never used go. I just upgraded but still unable to build.
No messages ... nothing when I issue the build command.

Please help!

![gojq build error](https://user-images.githubusercontent.com/1036163/71822055-de9aee80-30b9-11ea-8c65-2298233108fe.gif)

**Comment by SantoshSrinivas79** [comment]
@itchyny .. sorry! I think I figure out how the build works.

I had to move the binary:

```sh
mv ./go/bin/gojq /usr/local/bin/
```

The `gojq` build works now with `@csv`. `gojq 0.7.0 (rev: HEAD/go1.13.5)`
