### ISSUE TITLE
Sub and gsub functions

### ISSUE THREAD

**Issue by holyhope** [itchyny/gojq#201]
Hello,

I would like to use this library in my go code and I need that it supports all jq functions (at least version 1.6 would be nice).
If I am not wrong, [`sub`](https://stedolan.github.io/jq/manual/#sub(regex;tostring)sub(regex;string;flags)) and [`gsub`](https://stedolan.github.io/jq/manual/#gsub(regex;string),gsub(regex;string;flags)) are not yet implemented. Is it possible to add it please?

Thank you a lot.

**Comment by wader** [comment]
Hey, they are both implemented in gojq but use the regexp engine from golang standard library instead of Oniguruma (which i think is PCRE-compatible) so there are some differences.
```
$ gojq -n '"a" | sub("a";"b"), gsub("a";"b")'
"b"
"b"
```

**Comment by holyhope** [comment]
Oh yeah, sorry for the noise, it raised syntax error that I did not handled well.
