### ISSUE TITLE
first/1 and --stream

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#202]
[NOTE: THIS IS A NON-ISSUE -- the result of a typo.]

There seems to be something wrong with gojq's "streaming parser" when it is used with `first/1`, or vice versa.

The table below shows some performance metrics comparing jq and gojq when running a query
against a "real-world" JSON data set available at:

https://data.montgomerycountymd.gov/api/views/4mse-ku6q/rows.json

Its size is: 1,459,336,880 bytes, and it is archived at
https://web.archive.org/web/20230112063656/https://data.montgomerycountymd.gov/api/views/4mse-ku6q/rows.json

I suspect you could reproduce the problem quite easily with other large datasets in which the query result is obtained quickly by jq running a command similar to $CMD, where:

    CMD='first(inputs|select(length==2 and .[1]==["meta","view","createdAt"]))|.[1]'

Here are the performance numbers obtained using $CMD against the traffics violation dataset:

| u+s        |mrss (MB) | command
| ---------|----------|--------
| 221.4s   |    2.0   | jq -n --stream "$CMD"
| 697.8s   | 8051     | gojq -n --stream "$CMD"

Since gojq does print the correct value relatively promptly,
it seems clear that the main problem is that gojq is not exiting early: 
this would account for both the greater u+s time and the much greater memory consumption.

**Comment by itchyny** [comment]
I see there might be something wrong with memory management but it does not look like a bug of first/1. The command `gojq -n --stream 'first(inputs | select(length == 2 and .[1] >= 1000))' <(seq -f "%.0f" 10000000000)` exits quickly and works well, but when I change the query to `.[1] >= 100000000`, the memory consumption grows too much unlike jq. Maybe unused json values are not garbage collected, but I'm not sure what's the root cause. Well, time performance is not bad; gojq emits `[[],100000000]` in 1:22, while jq in 1:34. Needs more time for me to look into and any investigation is welcome.

**Comment by wader** [comment]
Got curious and did a mem profile of `gojq -n 'first(range(1000000000) | select(. >= 100000000))'` here is the biggest for the  "inuse space" set:

![Screenshot 2023-01-12 at 14 29 23](https://user-images.githubusercontent.com/185566/212079813-76fdb7b0-aaef-4e85-8da8-1ca299cae24c.png)

**Comment by pkoppstein** [comment]
@itchyny - The tell-tale sign that `first` and streaming are not working properly together is that in the example I gave, the answer is emitted almost immediately, but then processing continues.  Evidently, `first` is not effectively able to signal to gojq to STOP NOW in the way it does when streaming is not involved.

**Comment by itchyny** [comment]
If my command is not enough, please create reliable way to reproduce the issue. Your reported JSON is too large for my network to fetch correctly.
<img width="719" alt="Screenshot 2023-01-13 at 7 41 03" src="https://user-images.githubusercontent.com/375258/212196711-db35b4c4-fc7c-462e-b7ee-8a6023d78c02.png">

**Comment by pkoppstein** [comment]
@itchyny - It's only 1.5 GB.  Using wget it takes about 2.5 minutes to download:

    wget https://data.montgomerycountymd.gov/api/views/4mse-ku6q/rows.json

If wget is not working for you, could you try wget2 or curl?

**Comment by itchyny** [comment]
Well, I actually tried 5 times with all failures, maybe the server has timeout around 8 minutes. Their server always respond with Internal error.
```
 % wget https://data.montgomerycountymd.gov/api/views/4mse-ku6q/rows.json
--2023-01-13 08:39:18--  https://data.montgomerycountymd.gov/api/views/4mse-ku6q/rows.json
Resolving data.montgomerycountymd.gov (data.montgomerycountymd.gov)... 52.206.140.205, 52.206.140.199, 52.206.68.26
Connecting to data.montgomerycountymd.gov (data.montgomerycountymd.gov)|52.206.140.205|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘rows.json’

rows.json                               [                                                    <=>            ] 246.82M   545KB/s    in 8m 21s

2023-01-13 08:47:40 (504 KB/s) - ‘rows.json’ saved [258809927]

 % tail -c 100 rows.json
 Automobile", "2007", "TOYT",{
  "error" : true,
  "message" : "Internal error",
  "status" : 500
}

 % ping data.montgomerycountymd.gov
PING ext-lb-pool-1.aws.us-east-1-f-prod.socrata.net (52.206.68.26): 56 data bytes
64 bytes from 52.206.68.26: icmp_seq=0 ttl=42 time=191.831 ms
64 bytes from 52.206.68.26: icmp_seq=1 ttl=42 time=191.800 ms
64 bytes from 52.206.68.26: icmp_seq=2 ttl=42 time=192.203 ms
64 bytes from 52.206.68.26: icmp_seq=3 ttl=42 time=193.013 ms
64 bytes from 52.206.68.26: icmp_seq=4 ttl=42 time=192.023 ms
^C
--- ext-lb-pool-1.aws.us-east-1-f-prod.socrata.net ping statistics ---
5 packets transmitted, 5 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 191.800/192.174/193.013/0.444 ms

 % traceroute data.montgomerycountymd.gov
traceroute: Warning: data.montgomerycountymd.gov has multiple addresses; using 52.206.68.26
traceroute to ext-lb-pool-1.aws.us-east-1-f-prod.socrata.net (52.206.68.26), 64 hops max, 52 byte packets
 1  192.168.24.1 (192.168.24.1)  3.572 ms  3.069 ms  4.550 ms
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  osk004bb00.iij.net (58.138.106.185)  8.691 ms
    osk004bb01.iij.net (58.138.106.157)  10.145 ms
    osk011bb01.iij.net (58.138.81.69)  9.473 ms
 7  lax002bb12.iij.net (58.138.88.114)  122.045 ms
    lax002bb13.iij.net (58.138.88.126)  111.835 ms
    lax002bb12.iij.net (58.138.88.118)  116.853 ms
 8  abn001bb10.iij.net (58.138.81.234)  187.658 ms  187.170 ms
    abn001bb10.iij.net (58.138.81.242)  182.308 ms
 9  equinix02-iad2.amazon.com (206.126.236.35)  204.752 ms
    equinix01-iad2.amazon.com (206.126.236.68)  175.488 ms  176.742 ms
10  * * *
11  * * *
12  * * *
```

**Comment by pkoppstein** [comment]
@itchyny - 
I compressed the file (using bz2) and made it available on resilio:

The file: 139786726 Jan 11 4mse-rows.json.bz2

If you open the following link in a browser, it will guide you through the process:

https://link.resilio.com/#f=4mse-rows.json.bz2&t=6&i=BHGCKLIIEKL2E2Y7Y3B6NAOO5EMJW2AGI&e=1674183157&v=2.7

**Comment by pkoppstein** [comment]
@itchyny - You're right - my mis-report was based on a typo.  My apologies.  Would you mind if I simply deleted this entire issue (if that is possible?)
