### ISSUE TITLE
concurrency issue detected with go1.19

### ISSUE THREAD

**Issue by henderiw** [itchyny/gojq#204]
I ran into this issue using go version 1.19. Not sure if this is tested but reading and writing to a map can lead to this I believe

fatal error: concurrent map iteration and map write

goroutine 235 [running]:
github.com/itchyny/gojq.normalizeNumbers({0x22ed940?, 0xc0005e4360?})
        /Users/henderiw/go/pkg/mod/github.com/itchyny/gojq@v0.12.10/normalize.go:77 +0x105
github.com/itchyny/gojq.normalizeNumbers({0x22ed940?, 0xc0005e4330?})
        /Users/henderiw/go/pkg/mod/github.com/itchyny/gojq@v0.12.10/normalize.go:78 +0x6f1
github.com/itchyny/gojq.normalizeNumbers({0x22369c0?, 0xc00053e270?})
        /Users/henderiw/go/pkg/mod/github.com/itchyny/gojq@v0.12.10/normalize.go:73 +0x7d4
github.com/itchyny/gojq.(*Code).RunWithContext(0xc00010e500, {0x2773d50?, 0xc000042078}, {0x0, 0x0}, {0xc00054f030, 0x1, 0x1})
        /Users/henderiw/go/pkg/mod/github.com/itchyny/gojq@v0.12.10/compiler.go:50 +0x3b1
github.com/itchyny/gojq.(*Code).Run(...)
        /Users/henderiw/go/pkg/mod/github.com/itchyny/gojq@v0.12.10/compiler.go:39

**Comment by wader** [comment]
Hi, similar issue as in #188?

**Comment by itchyny** [comment]
Right, this looks like the same issue. For argument of Run, do not use values sharing same data between goroutines.
