### ISSUE TITLE
undocumented discrepancy re test/1

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#205]
On my Mac:
```
$ jq -n '"one\n" | test("^one$")'
true
$ gojq -n '"one\n" | test("^one$")'
false
```

**Comment by itchyny** [comment]
Firstly this looks like the multiline flag but
```
 $ jq -n '"one\ntwo" | test("^one$")'
false
```
What's happening...

**Comment by itchyny** [comment]
Noticed a similar issue is posted to jq simultaneously; https://github.com/stedolan/jq/issues/2534.
