### ISSUE TITLE
Is there a support for i/o  func

### ISSUE THREAD

**Issue by bulletblp4** [itchyny/gojq#21]
I am trying to run `jq -n '[inputs] | add'` over my json and it gives an error ```function not defined: inputs/0```

**Comment by itchyny** [comment]
This is what implemented just a day ago (see https://github.com/itchyny/gojq/commits/master), please wait for the next release.

**Comment by itchyny** [comment]
I released [v0.10.0](https://github.com/itchyny/gojq/releases/tag/v0.10.0) which implements `inputs` function. Please confirm.
