### ISSUE TITLE
Only getting `gojq: compile error: function not defined: keys_unsorted/0`

### ISSUE THREAD

**Issue by halostatue** [itchyny/gojq#210]
On macOS 13.2.1 with go 1.20.1, I am unable to use `gojq` for anything because of the error `gojq: compile error: function not defined: keys_unsorted/0`.

```console
❯ echo '1' | gojq .
gojq: compile error: function not defined: keys_unsorted/0
❯ echo '{ "foo": 123 }' | gojq .
gojq: compile error: function not defined: keys_unsorted/0
❯ echo '{ "foo": 123 }' | gojq keys
gojq: compile error: function not defined: keys_unsorted/0
❯ gojq --version
gojq 0.12.12 (rev: HEAD/go1.20.1)
```

I found this trying to use `gojq` with something more involved related to the AWS CLI:

```bash
aws ssm get-parameters-by-path \
  --path / --recursive |
  jq -r ".Parameters[].Name | select((. | startswith(\"/${env_name}/\")) and (. | endswith(\"/config\"))) | \"\t\" + ." |
  sort
```

`jq` is a wrapper function that calls `gojq` if it is detected and `jq` otherwise.

**Comment by itchyny** [comment]
The `keys_unsorted` function is not implemented in `gojq` as documented in [Difference to jq](https://github.com/itchyny/gojq#difference-to-jq). You might have configured jq configuration in `~/.jq` which contains `keys_unsorted`.

**Comment by halostatue** [comment]
Ah. That substantially decreases my ability to use `gojq` as it appears that there is no obvious way to suppress the reading and compilation of `~/.jq`.

Aside from removing `keys_unsorted` from this file, do you have any recommendations on how to fix this?

**Comment by itchyny** [comment]
Setting `$HOME` empty will help (`env HOME= gojq .`).
