### ISSUE TITLE
trailing comma's jq vs gojq

### ISSUE THREAD

**Issue by LeonB** [itchyny/gojq#25]
```
$ echo '{}' | gojq '{test1: 1, test2: 2,}'
gojq: invalid query: {test1: 1, test2: 2,}
    {test1: 1, test2: 2,}
                       ^  unexpected "," (expected "}")
```
```
$ echo '{}' | jq '{test1: 1, test2: 2,}'
{
  "test1": 1,
  "test2": 2
}
```

I don't know to what amount you want to keep compatibility with the original jq? We have a fairly large codebase of jq files where trailing comma's in objects are used quite a lot.

**Comment by itchyny** [comment]
I fixed the behavior in 0ada6fc1906272548153e9a3f7cd496beb17aabe, thanks.
