### ISSUE TITLE
error parsing regexp that contains "?<="

### ISSUE THREAD

**Issue by YuvalOmerRep** [itchyny/gojq#255]
Found a problem with gojq when calling match on a regex containing "?<="
example:
```
❯ gojq -n "@text \"projectP\" | match(\"(?<=project).\")"
gojq: invalid regular expression "(?P<=project).": error parsing regexp: invalid named capture: `(?P<=project).

❯ jq -n "@text \"projectP\" | match(\"(?<=project).\")"
{
  "offset": 7,
  "length": 1,
  "string": "P",
  "captures": []
}
```

This error seems to be caused by the following line in compileRegexp:
`re = strings.ReplaceAll(re, "(?<", "(?P<") `

**Comment by wader** [comment]
Hello, gojq uses https://pkg.go.dev/regexp for regexp which does not support looka-head/behind, jq uses https://github.com/kkos/oniguruma which do support it.

**Comment by itchyny** [comment]
Right, this is due to the difference of ragex engine.

**Comment by Birkman** [comment]
@itchyny , isn't it a bit misleading to call the module gojq, when it is not fully compliant with [jq](https://jqlang.github.io/jq/)?

**Comment by wader** [comment]
@YuvalOmerRep FYI the differences are documented here https://github.com/itchyny/gojq?tab=readme-ov-file#difference-to-jq
