### ISSUE TITLE
include "a" {search: "~/"};

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#265]
From the jq documentation regarding "search" paths:

> For paths starting with ~/, the user's home directory is substituted for ~.

Compare therefore:
```
$ jq -n -L. 'include "a" {search: "~/"}; a'
"Here"

$ gojq -n -L. 'include "a" {search: "~/"}; a'
gojq: compile error: function not defined: a/0
```

**Comment by itchyny** [comment]
Thanks for reporting.
