### ISSUE TITLE
New release for latest Go versions

### ISSUE THREAD

**Issue by GROwen** [itchyny/gojq#267]
_As a gojq user I would like to use a release compiled using the latest version of go to reduce the number of open CVEs affecting the program._

Just wondering if there's a release planned for the near future? I can see [this commit](https://github.com/itchyny/gojq/commit/470db58ade10408596f9f6318dbaeea792806df9#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddR24) has made it into the main branch. 🙏

**Comment by itchyny** [comment]
I will cut a release when I have free time. If there is a security issue in gojq, please let me know soon.

**Comment by GROwen** [comment]
Thanks for the quick response @itchyny , my report looks like our scanning workflow returning a false positive.

I've just run govulncheck over v0.12.16 and no vulnerabilities have been identified.

Thanks again.
