### ISSUE TITLE
[]int slices fail, expecting []any

### ISSUE THREAD

**Issue by JaviOverflow** [itchyny/gojq#269]
```
package main

import (
	"fmt"
	"log"

	"github.com/itchyny/gojq"
)

func main() {
	query, err := gojq.Parse(".[2]")
	if err != nil {
		log.Fatalln(err)
	}
	input := []int{1, 2, 3} // here
	iter := query.Run(input) // or query.RunWithContext
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			if err, ok := err.(*gojq.HaltError); ok && err.Value() == nil {
				break
			}
			log.Fatalln(err)
		}
		fmt.Printf("%#v\n", v)
	}
}
```

When input is a slice with a type other than any, it errors with the following:

```
2024/11/06 16:33:39 %!v(PANIC=Error method: invalid type: []int ([1 2 3]))
```

**Comment by wader** [comment]
Hey, i think this is by design. @itchyny commented about it here https://github.com/itchyny/gojq/issues/227#issuecomment-1786403524

**Comment by itchyny** [comment]
Currently, gojq only supports `[]any` for slices by design, so this is an expected behavior. Supporting any `[]T` type requires reflections in almost all filter implementations and it messes the code of the library, causes performance degradation.
