### ISSUE TITLE
Default moduleloader?

### ISSUE THREAD

**Issue by LeonB** [itchyny/gojq#27]
Would it be an idea to provide a default moduleloader by making [this moduleloader](https://github.com/itchyny/gojq/blob/master/cli/module.go#L13) public?

**Comment by itchyny** [comment]
May I ask the use case?

**Comment by LeonB** [comment]
Yeah, of course. I'm using gojq as a library. I'm trying to keep the (go)jq cli and library behaviour the same so it keeps testing little snippets easier for members on the team. At the moment I've copied the moduleloader from the cli package but I think it would be nice if I could just do:

``` go
gojq.WithModuleLoader(gojq.DefaultModuleLoader})
```

And it would also be nice to add '.' to the modulepath [like in the original jq](https://github.com/stedolan/jq/blob/abed751e9669ee716b04a8923413c4bc2734185d/src/linker.c#L230).

**Comment by itchyny** [comment]
I finally exported `gojq.NewModuleLoader`, please confirm.
