### ISSUE TITLE
How are numerics decoded?

### ISSUE THREAD

**Issue by andig** [itchyny/gojq#29]
It would be great to document how numerics (i.e. float and decimals) are decoded (float64? int? int64? depending on value?). This will make it easier to test for return types on client side.

**Comment by itchyny** [comment]
It depends on the value, either `float64`, `int` or `*big.Int`.

**Comment by andig** [comment]
Found normalize.go thanks to your hint. Seems int64 is in the mix, too if you look at https://github.com/itchyny/gojq/blob/31127e5603e957ae0b34d1adec1dd386b6c55a63/normalize.go#L31?

**Comment by itchyny** [comment]
That line returns int type as well. Seems assuming 64bit platform though.

**Comment by andig** [comment]
I'm using some helper methods to work with these- maybe they are helpful and would suit this library:

	// Float64 converts interface to float64
	func Float64(v interface{}) (float64, error) {
		switch v := v.(type) {
		case int:
			return float64(v), nil
		case float64:
			return v, nil
		default:
			return 0, fmt.Errorf("unexpected float type: %T", v)
		}
	}

	// Int64 converts interface to int64
	func Int64(v interface{}) (int64, error) {
		switch v := v.(type) {
		case int:
			return int64(v), nil
		case float64:
			if float64(int64(v)) == v {
				return int64(v), nil
			}
			return 0, fmt.Errorf("unexpected int64: %v", v)
		default:
			return 0, fmt.Errorf("unexpected int64 type: %T", v)
		}
	}

	// String converts interface to string
	func String(v interface{}) (string, error) {
		switch v := v.(type) {
		case string:
			return v, nil
		default:
			return "", fmt.Errorf("unexpected string type: %T", v)
		}
	}

	// Bool converts interface to bool
	func Bool(v interface{}) (bool, error) {
		switch v := v.(type) {
		case bool:
			return v, nil
		default:
			return false, fmt.Errorf("unexpected bool type: %T", v)
		}
	}
