### ISSUE TITLE
How to use Iterator to differentiate between array with single element vs a single element

### ISSUE THREAD

**Issue by NeenuAVarghese** [itchyny/gojq#30]
How do I differentiate between array with single element vs a single element from the Iterator of a query ?

```golang
package main

import (
	"fmt"
	"log"

	"github.com/itchyny/gojq"
)

func main() {
	query, err := gojq.Parse(".tags[].name")
	if err != nil {
		log.Fatalln(err)
	}
	input := map[string]interface{}{
		"kind": "do#droplets",
		"href": "/droplets/123",
		"tags": []interface{}{
			map[string]interface{}{
				"name": "hello",
			},
			map[string]interface{}{
				"name": "goodbye",
			},
		},
	}
	iter := query.Run(input)
	var result []interface{}
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			log.Fatalln(err)
		}
		if v != nil {
			result = append(result, v)
		}
	}
	fmt.Println(result)
}
```
**Output: [hello goodbye]**

Now, if I modify the input,
```golang
package main

import (
	"fmt"
	"log"

	"github.com/itchyny/gojq"
)

func main() {
	query, err := gojq.Parse(".tags[].name")
	if err != nil {
		log.Fatalln(err)
	}
	input := map[string]interface{}{
		"kind": "do#droplets",
		"href": "/droplets/123",
		"tags": []interface{}{
			map[string]interface{}{
				"name": "hello",
			},
		},
	}
	iter := query.Run(input)
	var result []interface{}
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			log.Fatalln(err)
		}
		if v != nil {
			result = append(result, v)
		}
	}
	fmt.Println(result)
}
```
**Output : [hello]**

Output in both cases is an array. Now, if I change the path and set it to `.href`, I still get an array:

```golang
package main

import (
	"fmt"
	"log"

	"github.com/itchyny/gojq"
)

func main() {
	query, err := gojq.Parse(".href")
	if err != nil {
		log.Fatalln(err)
	}
	input := map[string]interface{}{
		"kind": "do#droplets",
		"href": "/droplets/123",
		"tags": []interface{}{
			map[string]interface{}{
				"name": "hello",
			},
		},
	}
	iter := query.Run(input)
	var result []interface{}
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			log.Fatalln(err)
		}
		if v != nil {
			result = append(result, v)
		}
	}
	fmt.Println(result)
}
```
**Output: [/droplets/123]**

I want to be able to differentiate between Iterators which is an array of one element vs an Iterator that should be giving me a single value. Is there a good way of handling this using this library ?

**Comment by itchyny** [comment]
These cases are indistinguishable in principle because every single value in jq semantics is an iterator emitting one value. You get an array because you're appending to the `result`, but you can just break the for loop after getting one value to get a single element. So correcting the title, *between a single element from an iterator vs a single element* and the answer is, indistinguishable.

**Comment by NeenuAVarghese** [comment]
> but you can just break the for loop after getting one value to get a single element

yeah, I can do that. But, How do I decide when to break ? 

The problem is that the Iterator does not give us any information of the underlying data format. In the above examples, we know that the value out of `.href` is supposed to be a single element as opposed to `.tags[].name` which could return an array.

**Comment by douglaswth** [comment]
I think that given a single input document, you can reason about whether a query would return an iterator that will always give a single value, an iterator that could return multiple values, or if it would be ambiguous:

1. `.href` is a simple query that would always give a single value iterator for a given document
2. `.[].href` is a simple query that could return multiple values
3. Given more complex queries it might require reasoning about multiple branches, but even in that case, if one branch can return a multi value iterator, then perhaps we should say that the whole branch statement can as well

**Comment by itchyny** [comment]
Yeah, please don't be confused, `.tags[].name` does not return an array. It may return multiple values, a single element, or nothing. So you're saying the way of distinguishing an iterator which always emits an element and an iterator which emits unpredictable number of elements. `if .foo then .href else .[].href` can be both.

**Comment by itchyny** [comment]
Note that the interpreter does no distinguish them on runtime. Considering everything an iterator simplifies the interpretation of jq semantics. For example, in a query `[ .foo, 10, .[], .. ]`, considering `.foo`, `10`, `.[]`, `..` are all iterators, `[ ]` is an operator which constructs an array from multiple iterators.

**Comment by itchyny** [comment]
I think this is statically determined and was thinking of a static type system in jq language, but it'll require lots of work. I don't think I will implement this so closing.
