### ISSUE TITLE
Updating paths can be slow compared to jq

### ISSUE THREAD

**Issue by LeonB** [itchyny/gojq#32]
Counting with jq:

``` sh
$ time cat test2.json | jq '[.Bills[].Revenue[].Amount] | length'
777

real	0m0,096s
user	0m0,094s
sys	0m0,009s
```

Counting with gojq

``` sh
$ time cat test2.json | gojq '[.Bills[].Revenue[].Amount] | length'
777

real	0m0,078s
user	0m0,082s
sys	0m0,018s
```
Updating with jq:

``` sh
$ time cat test2.json | jq '.Bills[].Revenue[].Amount |= "TEST"' > /dev/null

real	0m0,131s
user	0m0,131s
sys	0m0,009s
```

Updating with gojq:

``` sh
$ time cat test2.json | gojq '.Bills[].Revenue[].Amount |= "TEST"' > /dev/null

real	0m3,256s
user	0m5,475s
sys	0m0,676s
```
Updating when using map (gojq)

``` sh
$ time cat test2.json | gojq '.Bills |= map(.Revenue |= map(.Amount = "TEST"))' > /dev/null

real	0m0,163s
user	0m0,227s
sys	0m0,017s
```

It looks like it's getting slower the more data is in the parent nodes. Even if those aren't updated / touched.

In can provide the test file but I'd rather not share it publicly.

**Comment by itchyny** [comment]
I'm sure I thought the deep cloning would cause this kind of performance issue when I wrote the code. I changed the implementation of `setpath` and `delpaths` so this issue has been fixed. Thanks for reporting.

**Comment by LeonB** [comment]
Thanks! MUCH quicker. I've had a similar issue with `add` but I'll open another issue for that. Thanks for all the hard work!
