### ISSUE TITLE
add(): difference with jq when operating on object

### ISSUE THREAD

**Issue by LeonB** [itchyny/gojq#34]
I don't really think the jq behaviour is better. I like gojq's error better but I thought I should report the difference:

``` sh
$ echo '{}' | jq '{"category": 4, "ding": 3} | add'
7
```

``` sh
$ echo '{}' | gojq '{"category": 4, "ding": 3} | add'
gojq: add cannot be applied to: object ({"category":4,"ding":3})
```

**Comment by itchyny** [comment]
Ah, ok, this is a regression of 95d65385ef440eb1e8033f68fe291f18a40859d7.
