### ISSUE TITLE
Memory leak with group_by

### ISSUE THREAD

**Issue by Egrn** [itchyny/gojq#42]
Big flat struct on input like `{app_name,app_propertie1,...}` and query like `.|group_by(.app_name)` resulting abnormal memory consumption.

**Comment by itchyny** [comment]
Please describe the issue with actual data and how much it used the memory so that anyone can reproduce. Also confirm that the version is newer than [v0.10.2](https://github.com/itchyny/gojq/releases/tag/v0.10.2).

**Comment by Egrn** [comment]
@itchyny thank you! Excuse me for inattention. 

With v0.11.1 benchs became:
BENCHMARK: memory alocation before/after TransformJson in MB: 406/577

but befor (v0.10.1) it was like 400/3500 MB

**Comment by itchyny** [comment]
So 70MB data results 171MB increase, that's not surprising. You mean you're using gojq as a library and the data is not garbage collected? How do you handle the data?

**Comment by Egrn** [comment]
The reason for issue was leak on level 400MB before transform / 3500MB after. In v0.11.1 it is fixed and consumption level fluctuate about 100MB. By the way, processing speed increased multiple.  My query and iterator behind
`		.
		|group_by(.app_name)
		|map({
			app_name: map(.app_name)|.[0],
			appl_id: map(.appl_id)|.[0],
			infsys_name: map(.infsys_name)|.[0],
			contexts: .
					|group_by(.context_name)
					|map({
						context_name:
							map(.context_name)|.[0],
							request_time:map(.request_time)|.[0],
							records: .
								|map({
									primary_key,
									properties
								})
					})
					|map({
						(.context_name):{
							request_time,
							records
						}
					})|add
		})
		|map({
			(.app_name): .
		})|add`

`func TransformJson(applicationsData *interface{}, q string) (interface{}, error) {

	jqQuery, err := gojq.Parse(q)
	if err != nil {
		return nil, err
	}

	var result interface{}
	iterGroup := jqQuery.Run(*applicationsData)
	for {
		v, ok := iterGroup.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			return nil, err
		}
		result = v
	}
	return result, nil
}

func ToMb(b uint64) uint64 {
	return b / 1024 / 1024
}`

**Comment by itchyny** [comment]
> By the way, processing speed increased multiple.  

Your report lacks measurement results again, how does it scale against the input size? Your query uses 3 nested maps so it may cost O(n³).

**Comment by Egrn** [comment]
Measurement is a result of calls `runtime.ReadMemStats(&mem)` befor and after TransformJson.
3 nested maps does't important cost with last version of lib

**Comment by itchyny** [comment]
So what did you get about processing speed?

**Comment by Egrn** [comment]
77.9MB

0.10.1
BENCHMARK: start json transformation after 6.85663638s"}
BENCHMARK: memory alocation before TransformJson in MB: 432"}
BENCHMARK: json transformation is done after 3m50.227196437s"}
BENCHMARK: memory alocation after TransformJson func in MB: 3396"}

0.11.1
BENCHMARK: start json transformation after 7.003748137s"}
BENCHMARK: memory alocation before TransformJson in MB: 431"}
BENCHMARK: json transformation is done after 7.993057774s"}
BENCHMARK: memory alocation after TransformJson func in MB: 441"}

**Comment by itchyny** [comment]
Thank you. I see nothing wrong with the profiling result. So closing this issue.
