### ISSUE TITLE
Support own types using Array and Object interfaces

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#44]
Hi, i wonder if it would be possible to support go types in the input data structure that implements a array or object interface.

Something like this
```go
type JsonArray interface {
    Length() int
    Index(index i) interface{}
}

type JsonObject interface {
    Length() int
    Property(name string) interface{}
}

type CustomObject struct{}

func (CustomObject) Length() int { return 1 }

func (CustomObject) Property(name string) interface{} {
    switch name {
        case "a":
            return 123
        default:
            return nil
    }
}

func Test() {
    query, _ := gojq.Parse(".foo.a")
    input := map[string]interface{}{"foo": CustomObject{}}
    iter := query.Run(input)
    v, ok := iter.Next() // v would be 123
}
```

**Comment by itchyny** [comment]
This is unlikely to be implemented. It is too hard for me to keep maintenance of making this stuff work in all type switches while there's no benefit for myself. You can convert your type to `[]interface{}` and `map[string]interface{}` and pass it to gojq library.

**Comment by wader** [comment]
Ok! understand
