### ISSUE TITLE
Support for hex, octal and binary number literals

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#47]
Hi, i've thought about adding support for hex, octal and binary number literals. Is that something you would be interested in?

I understand if you don't want to add extensions and non-compatible things to gojq compared to jq. Would an option be to make such things disable by default? but maybe messy to do with some features?

**Comment by wader** [comment]
Maybe this issue is interesting https://github.com/stedolan/jq/issues/1632

In my case i would want to have literals instead of function(s) to convert from a string. Im using gojq in projects that deal with lots of hex and binary data and position so would be very nice if it was easy to write queries using it.

**Comment by itchyny** [comment]
Basically current gojq syntax (AST, lexer and parser) is intended to be compatible with jq. Introducing flags to the parser is a mess for me. I understand these literals are sometimes important but I would not implement until jq implements it in its main branch. Common literal syntax exists but when jq introduced in a different way, it would break your gojq scripts. So proposal to jq should be the first. By the way, I found https://golang.org/design/19308-number-literals is a good material on this topic.

**Comment by wader** [comment]
Make sense. Yes doing optional things in the lexer/parser sounds very messy.

Thanks for the link. Think it's ok for my project to be incompatible for now so maybe i will do a fork and add things, not sure yet. I can keep you updated what happens.
