### ISSUE TITLE
Inconsistent filenames in release binaries

### ISSUE THREAD

**Issue by smlx** [itchyny/gojq#49]
Thanks for the awesome tool!

Is there a particular reason for creating the release binaries as `.zip` for macOS and `.tar.gz` for Linux? And would there be any chance of changing this to use `.tar.gz` for both?

I'm writing a script that pulls down gojq as part of CI, and I have to write a special case to work around this inconsistency.

**Comment by itchyny** [comment]
Currently it follows the defaults of [goxz](https://github.com/Songmu/goxz/#archive-naming-specification). I wouldn't change them to `.tar.gz` for _consistency_, I rather prefer `.zip` and Linux archive is an exception (follows historical conventions). It will also make unarchive difficult on Windows.

**Comment by smlx** [comment]
Ok, thanks for the explanation :+1:
