### ISSUE TITLE
How to get the complete json string after modifying the value of json?

### ISSUE THREAD

**Issue by hycchen** [itchyny/gojq#5]
Use the following test json in jq: `{"test":"test1","student":[{"name":"Luffy","age":17},{"name":"Pikachu","age":1},{"name":"Gintoki","age":25}]}`
Enter the command `(.student | .[] | select( .name == "Pikachu" ) | .age ) = 100`
Will get the following result
![image](https://user-images.githubusercontent.com/49049230/70521256-dbbfe300-1b79-11ea-8bf9-15b82031518a.png)
But in gojq, you will get error: gojq: gojq: invalid path against: object ({"age":1,"name":"Pikac ...)
This is due to the inconsistency between the values of args [0] and env.paths.top () in the function at github.com/itchyny/gojq.(*env).pathEntries at execute.go. index has not changed since the last round of execution.
How to get the complete json string after modifying the value of json?

**Comment by itchyny** [comment]
Thanks for issue report. I'm sure the invalid path detection is buggy in gojq and knew that it should have this kind of bug.  I want to fix this but I remember that the original version of jq relies on the pointer comparison for this detection and I found it difficult to implement in Go. I have to take time to find a better solution.

**Comment by itchyny** [comment]
Hmm, it seems that ignoring the path check does not solve the problem... Still investigating...
```
echo '[{"name":"Luffy","age":17},{"name":"Pikachu","age":1},{"name":"Gintoki","age":25}]' | \
  ./gojq '(.[] | select(.name == "Pikachu") | .age) = 100'
gojq: expected an object but got: string ("Pikachu")
```

**Comment by itchyny** [comment]
This is now been fixed.

**Comment by itchyny** [comment]
This has been fixed now.
