### ISSUE TITLE
missing implementation of keys_unsorted

### ISSUE THREAD

**Issue by omadawn** [itchyny/gojq#50]
gojq: compile error: function not defined: keys_unsorted/0

jq has at least one very awkward default behavior.
`.[]` and `keys` sort things in very different ways

`.[]` enumerates values based on the keys input order
`keys` enumerates values alphabetically https://jqplay.org/jq?q=keys&j={%22foo%22%3A%201%2C%20%22abc%22%3A%202%2C%20%22abcd%22%3A%203%2C%20%22Fe%22%3A%204}

jq 1.5 introduced `keys_unsorted` which enumerates values the same way that .[] does.
https://jqplay.org/jq?q=keys_unsorted&j={%22foo%22%3A%201%2C%20%22abc%22%3A%202%2C%20%22abcd%22%3A%203%2C%20%22Fe%22%3A%204}

**Comment by itchyny** [comment]
gojq cannot implement `keys_unsorted` function because it uses `map[string]interface{}` to represent JSON object so it does not keep the order. Currently there is no plan to implement ordered map so I do not implement this function.
