### ISSUE TITLE
Using the library like the cmdline

### ISSUE THREAD

**Issue by lukepon** [itchyny/gojq#52]
Hi,

I'm having difficulty reading how to use the library. I can use gojq in the shell just fine but I thought I'd dive into how you managed to do some things but I can't manage.

For instance:
`echo '[{"how":"does", "this":"work"},{"how":"does", "this":"work"}]' | gojq '.[]'
{
  "how": "does",
  "this": "work"
}
{
  "how": "does",
  "this": "work"
}`

I tried just following the example in the docs to this: 

`     
       body := `[{"how":"does", "this":"work"},{"how":"does", "this":"work"}]`
       
       query, err := gojq.Parse(".[]")
	if err != nil {
		log.Error(err)
	}
	input := []interface{}{body}
	iter := query.Run(input)
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			log.Error(err)
		}
		ioutil.WriteFile("tester.json", []byte(fmt.Sprint(v)), 0644)
		fmt.Printf("%#v\n", v)
	}`
	
But this just prints out the same object. 

Is there anyone who can offer some suggestions on what I'm doing wrong and if time permits where I should be looking in the package for why it doesn't work.

**Comment by itchyny** [comment]
What you are doing is giving the JSON as a string input. You need to decode to an interface.
```go
	var input interface{}
	json.Unmarshal([]byte(`[{"how":"does", "this":"work"},{"how":"does", "this":"work"}]`), &input)
```

**Comment by lukepon** [comment]
@itchyny thanks, sorry it took long to reply, I overlooked that the interface{} was in fact just that (the new output with your edit in _tester.json_:)

`
map[string]interface {}{"how":"does", "this":"work"}
 map[string]interface {}{"how":"does", "this":"work"}
`

I was trying to create a newline delimited JSON from an array that I'm GETting. I think this package is beyond my abilities at the moment.

**Comment by itchyny** [comment]
You don't need to use gojq.
```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	var input []interface{}
	json.Unmarshal([]byte(`[{"how":"does", "this":"work"},{"how":"does", "this":"work"}]`), &input)
	for _, x := range input {
		xs, _ := json.Marshal(x)
		fmt.Println(string(xs))
	}
}
```

**Comment by lukepon** [comment]
Thank you @itchyny! That's really nice of you. I didn't think of using the interface, that helps make it more generic (which is why I was looking at gojq for an implementation of an iterator). I ended up doing this:

`
        var ndJSONMarshalled []byte
	var arrayOfStrings []string
	var input []interface{}
	err := json.Unmarshal([]byte(body), &input)
	if err != nil {
		..
	}

	for _, line := range input {
		s, err := json.Marshal(line)
		if err != nil {
			..
		}
		arrayOfStrings = append(arrayOfStrings, string(s))

	}
	newLineJSONString := strings.Join(arrayOfStrings, "\n")
	newLineJSONBytes, err := ioutil.ReadAll(strings.NewReader(newLineJSONString))
	if err != nil {
		..
	}
	ndJSONMarshalled = append(ndJSONMarshalled, newLineJSONBytes...)
	// ioutil.WriteFile("tester.json", ndJSONMarshalled, 0644)
`

It works but it feels inefficient because I'm switching from strings to []byte so many times.

**Comment by itchyny** [comment]
1. You don't need to `ioutil.ReadAll(strings.NewReader` to convert a string to bytes. Just `[]byte(str)`. Still allocation occurs though.
2. `strings.Join` is inefficient than using `strings.Builder`.
3. Anyway, building the JSON string (or bytes) allocates successive memory. You can write to the file.

```go
package main

import (
	"encoding/json"
	"log"
	"os"
)

func main() {
	body := `[{"how":"does", "this":"work"},{"how":"does", "this":"work"}]`
	f, err := os.Create("test.json")
	if err != nil {
		log.Fatal(err)
	}
	var input []interface{}
	if err := json.Unmarshal([]byte(body), &input); err != nil {
		log.Fatal(err)
	}
	enc := json.NewEncoder(f)
	for _, x := range input {
		if err := enc.Encode(x); err != nil {
			log.Fatal(err)
		}
	}
}
```
Good luck.

**Comment by lukepon** [comment]
Thank you so much! You're a hero! I'm going to investigate how this works.
