### ISSUE TITLE
question: Is *Code.Run() safe to use in goroutines?

### ISSUE THREAD

**Issue by simonmittag** [itchyny/gojq#54]
I'm compiling a jq expression with this method: https://pkg.go.dev/github.com/itchyny/gojq#Compile

```
query, _ := gojq.Parse(".foo | ..")
code, _ := gojq.Compile(query)

for i:=0;i<10;i++ {
  go func() {
    code.Run(input)
  }()
}
```

is the above safe with goroutines?

**Comment by itchyny** [comment]
Yes, it's safe to call `code.Run` in goroutines. [`code.codes` and `code.codeinfos`](https://github.com/itchyny/gojq/blob/v0.11.2/execute.go#L10-L11) are shared in `*env` but there is no write against them.

**Comment by simonmittag** [comment]
Nice! It takes only 8μs precompiled for my use case of parsing jwt tokens, see: https://github.com/simonmittag/j8a/blob/master/proxy_test.go

Cheers for bringing jq to golang. I included it in my project above.
