### ISSUE TITLE
String format query with no operator using %#v or %#+v panics

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#56]
Hi, was digging around trying to learn more about the gojq query AST type and noticed panics for some queries when I tried to print them using `log.Printf("var: %#+v\n", var)` (the `lv` snippet in vscode). The panic happens because the expression has no operator and panics in `func (Operator) String()`.

Example:
```go
package main

import (
	"log"

	"github.com/itchyny/gojq"
)

func main() {
	q, err := gojq.Parse("a")
	if err != nil {
		panic(err)
	}
	log.Printf("q: %#+v\n", q)
}
```

Would it make sense that queries that  parses successfully should be formattable like this? but I understand the panic make sense to have also. Maybe a new operator enum `OpNone` etc?

**Comment by itchyny** [comment]
The issue is about `func (Operator) GoString()`, not `func (Operator) String()`. Adding new operator for zero value is not a good solution as a workaround for debugging purpose.

**Comment by wader** [comment]
Ah yes sorry wrong method. I was thinking a non-zero `OpNone` that the parser assigns when parsing.
