### ISSUE TITLE
Fails when $HOME unset

### ISSUE THREAD

**Issue by thumphries** [itchyny/gojq#58]
If `$HOME` is unset, gojq exits with error `$HOME is not defined`

I realise this situation is uncommon (I'm running gojq as a CLI tool inside an AWS Lambda) and have worked around it but thought it might be worth reporting anyhow...

Thanks for the tool, works great!

**Comment by itchyny** [comment]
Okay, thanks for reporting! This is surely troublesome in some situation.

**Comment by itchyny** [comment]
The fixed version will be released in a few days.

**Comment by thumphries** [comment]
Wow, nice! Thanks again
