### ISSUE TITLE
Ideas: jqfmt, vet and lint

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#62]
Hi, something similar to `gofmt` would be nice and make it possible to write IDE extensions that does auto formatting. I guess one tricky bit would be to allow preserves some formatting like some new lines etc?

Vet and lint might be nice also but haven't thought so much about what kind of errors they could find.

**Comment by itchyny** [comment]
This is an interesting idea and I have considered for the design before, but currently I don't have strong motivation for implementing this. The main target of the project is for cli user and library user. Once I actually wanted to reformat [builtin.jq](https://github.com/itchyny/gojq/blob/master/builtin.jq) using gojq itself, but such thing is a minor use-case compared to other languages (unfortunately!) and does not meet the maintenance cost.

**Comment by noperator** [comment]
Hi, @wader. I took a stab at `jqfmt` here: https://github.com/noperator/jqfmt. Let me know what you think!

<p align="center">
<img width="400px"  src="https://camo.githubusercontent.com/4f37816447f99e13860d30c6ed3cae72d0e78778933154ef6e8e84bf96737f28/68747470733a2f2f692e696d6775722e636f6d2f736749493163652e706e67"/>
</p>

**Comment by noperator** [comment]
Thanks 🙂 Do I gather correctly that you've implemented a walkable AST in jqjq?

**Comment by wader** [comment]
> Thanks 🙂 Do I gather correctly that you've implemented a walkable AST in jqjq?

By walkable do you mean if there is a function like `walk(<AST>; <function to call for each node>)`? then no it does not, but the eval code might be interesting to look at? jq-lsp do have something like that https://github.com/wader/jq-lsp/blob/master/lsp/lsp.jq#L213 but it works as generator that outputs all node and their scope.

If you want to see how how jqjq's internal AST looks like (it's inspired by gojq's AST) you can use `--parse`:
```sh
$ ./jqjq --parse '123 | type'
{
  "op": "|",
  "left": {
    "term": {
      "number": "123",
      "type": "TermTypeNumber"
    }
  },
  "right": {
    "term": {
      "type": "TermTypeFunc",
      "func": {
        "name": "type"
      }
    }
  }
}
```
(same can be done with fq using gojq's parser `fq -n '"123 | type" | _query_fromstring'` and there is also `_query_tostring` and bunch more functions, might be useful for playing around)

Note that jqjq's lexer and parser current it very much written to handle only valid syntax. If something goes wrong it will do a bad job at explaining what went wrong and where, so probably not great for building a linter or formatter at the moment. But i did start writing some code turn a AST back into a string some time ago https://github.com/wader/jqjq/commit/9aa94ff523d2079a02161ee27c01eedfb454d06b
