### ISSUE TITLE
Export EmptyError for convenience

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#64]
Hi, would it make sense to export something similar to `goqj/cli.emptyError` as `gojq.EmptyError` and maybe also add a check for it in the op execution so that it does not need to be checked for in the `Iter` loop?

Im using it to implement something similar to `empty` and `select` but feels a bit strange.

**Comment by itchyny** [comment]
I'm not sure what's the precise issue and what you want. Can you describe with sample code?

**Comment by wader** [comment]
Im experimenting with custom functions that behave like `select` and currently i'm doing it by returning and `emptyError` and ignoring it in the iteration loop, like how gojq cli code does it. I was thinking if it would make sene to support this in the library code instead.

Will post some example code later today when i get time.

**Comment by itchyny** [comment]
In general, jq functions like `empty`, `select` (or any functions including `,` operator) cannot be implemented by custom internal functions. What you need is custom jq functions.

**Comment by wader** [comment]
Hi again, yes understand. Here is the example. If I understand the code in `env.Next()` returning a special error and ignoring it should behave very similar to `empty` (`opbacktrack`), but maybe i'm missing something?

By custom jq functions you mean normal jq `def` functions?

Thanks for taking your time to answer my question.

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"github.com/itchyny/gojq"
)

type EmptyError interface {
	IsEmptyError() bool
}

type ErrEmpty struct{}

func (ErrEmpty) Error() string      { return "" }
func (ErrEmpty) IsEmptyError() bool { return true }

func main() {
	query, err := gojq.Parse(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return
	}

	code, err := gojq.Compile(query,
		gojq.WithFunction("filter_null", 0, 0, func(c interface{}, a []interface{}) interface{} {
			if c == nil {
				return ErrEmpty{}
			}
			return c
		}),
	)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return
	}

	iter := code.RunWithContext(context.Background(), nil)
	for {
		var ok bool
		var v interface{}

		if v, ok = iter.Next(); !ok {
			break
		}
		if err, ok = v.(error); ok {
			if ee, ok := err.(EmptyError); ok && ee.IsEmptyError() {
				continue
			}
			fmt.Fprintln(os.Stderr, err)
			break
		}

		e := json.NewEncoder(os.Stdout)
		e.SetIndent("", "    ")
		_ = e.Encode(v)
	}
}
```
```sh
$ go run main.go '1,null,3 | filter_null'
1
3
```

**Comment by itchyny** [comment]
Returning an empty error is not equal to backtracking, `[1,null,3]|.[]|try filter_null catch .` is not equal to `[1,null,3]|.[]|try select(.!=null) catch .` for example. Simplest way to add jq functions is to prepend them against user's query.
```go
const customFunctions = "def filter_null: select(. != null);"

func main() {
	query, err := gojq.Parse(customFunctions + os.Args[1])
```
