### ISSUE TITLE
Try-catch with custom function

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#65]
Hi!

I was doing some custom functions that felt like good fit to be `try`:able on error. Did some quick experimentation by exporting `gojq.exitCodeError` as `gojq.ExitCodeError` that would enable a custom function to do this:

```go
func customFn(c interface{}, a []interface{}) interface{} {
	return &gojq.ExitCodeError{
		Value: ...,
	}
}
```
Seems to work as expected.

Would that kind of functionality make sense? maybe should be done by checking if errors implement a tryable/catchable-interface somehow?

Another related question. I tried to understad what the significance of `exitCodeError.code = 5` has, just a random constant for tests or something else?

**Comment by itchyny** [comment]
Throw any error, that will be caught by `try`. So exporting `exitCodeError` doesn't make sense.
```go
package main

import (
	"errors"
	"fmt"
	"log"

	"github.com/itchyny/gojq"
)

func main() {
	query, err := gojq.Parse("try f catch .")
	if err != nil {
		log.Fatalln(err)
	}
	code, err := gojq.Compile(
		query,
		gojq.WithFunction("f", 0, 0,
			func(v interface{}, _ []interface{}) interface{} {
				return errors.New("error: custom error")
			},
		))
	if err != nil {
		log.Fatalln(err)
	}
	iter := code.Run(nil)
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			log.Fatalln(err)
		}
		fmt.Printf("%#v\n", v)
	}
}
```
5 is not a random exit code. It follows the jq specification (exit codes 1 through 5 have each meaning in jq).
```sh
 % jq -n '"x" | error'; echo $?
jq: error (at <unknown>): x
5
```

**Comment by wader** [comment]
Aha sorry I must have tested it wrongly somehow. But I was probably a bit unclear that I wanted to be able to throw any value, currently with `error` you catch the `Error()` string. So something like this:
```jq
$ jq -n 'try error({a: "some value"}) catch .'
{
  "a": "some value"
}
```
In my example the custom function would return `&gojq.ExitCodeError{Value: map[string]interface{}{"a": "some value"}` to get the same behaviour.

**Comment by itchyny** [comment]
Okay, let me think for a few days. Maybe `interface{ ErrorValue() interface{} }` would fit.

**Comment by itchyny** [comment]
I implemented the `catch` handler to use the error value when the error implements the following interface. 
```go
type ValueError interface {
	error
	Value() interface{}
}
```

**Comment by wader** [comment]
Ok, thanks!
