### ISSUE TITLE
Colorized output for YAML

### ISSUE THREAD

**Issue by jtyr** [itchyny/gojq#66]
It would be great if `gojq` could produce colorized output even when `--yaml-output` is specified.

**Comment by itchyny** [comment]
Understandable feature request, but unlikely to be implemented because the [yaml package](https://pkg.go.dev/gopkg.in/yaml.v3) does not support colorization, and I don't want to write coloring marshaler from scratch.

**Comment by jtyr** [comment]
@itchyny what about to use https://github.com/goccy/go-yaml? It supports coloring.
