### ISSUE TITLE
Feature request: create a cui

### ISSUE THREAD

**Issue by fugkco** [itchyny/gojq#74]
Saw #67, and as I mentioned, having a repl is a great thought. As a next step to this, utilising https://github.com/jesseduffield/gocui or something similar to create a ui would be awesome. Being able to do `cat file.json | gojq --interactive` so we can construct the query will make life so much easier. Possibly with completion, but that feels like it would be a lot more work.

**Comment by itchyny** [comment]
I like interactive filtering tools in terminal but it does not fit to this project so implement as another cli tool. Improving and some extensions to the library is welcome. But the cli tool gojq is just another implementation of jq, with slight extensions (umm, supporting YAML was not _slight_ though). Interactive cli tool requires lots of code and probably with dependencies.

**Comment by fugkco** [comment]
Cool, yeah I figure it'll probably a separate utility anyway. Thanks!
