### ISSUE TITLE
Support for JWK and JWT

### ISSUE THREAD

**Issue by thoughtful-solutions** [itchyny/gojq#75]
JSON Web Tokens are an open, industry standard RFC 7519 method for representing claims securely between two parties. The ability to take JSON content and produce JWTs would be extremely useful

The ability to encrypt and decrypt JSON Web Key (JWK) which JavaScript Object Notation (JSON) [RFC7159] data structure that represents a cryptographic key for existing JSON or new JSON objects.

**Comment by itchyny** [comment]
The issue does not fit to gojq, which is just an another implementation of jq.
