### ISSUE TITLE
string + operator crashes

### ISSUE THREAD

**Issue by baileybunch5dad** [itchyny/gojq#76]
Example working in JQ

without +

root@go-devenv:/c/dev# jq '.items[] | .name, .id' < reporttypes.json
"DUR"
"50a5b422-64ac-482c-890f-dd9d548f10af"
"CFGap"
"e25415ff-2278-4040-b1ea-085c1a122690"

With +

root@go-devenv:/c/dev# jq '.items[] | .name+"_tmp", .id' < reporttypes.json
"DUR_tmp"
"50a5b422-64ac-482c-890f-dd9d548f10af"
"CFGap_tmp"
"e25415ff-2278-4040-b1ea-085c1a122690"

But running inside Go

goroutine 1 [running]:
github.com/itchyny/gojq.(*compiler).compile(0xc00009e210, 0x0, 0xc00008c8e0, 0x4d5ed7)
	C:/Users/chris/go/src/github.com/itchyny/gojq/compiler.go:137 +0x1df
github.com/itchyny/gojq.Compile(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/chris/go/src/github.com/itchyny/gojq/compiler.go:117 +0x1d4
github.com/itchyny/gojq.(*Query).RunWithContext(0x0, 0x0, 0x0, 0x5cfee0, 0xc0000a0060, 0x0, 0x0)
	C:/Users/chris/go/src/github.com/itchyny/gojq/query.go:31 +0x47
github.com/itchyny/gojq.(*Query).Run(...)
	C:/Users/chris/go/src/github.com/itchyny/gojq/query.go:26
main.main()
	C:/dev/csvsplit/csvsplit.go:52 +0x131

**Comment by baileybunch5dad** [comment]
In making a small standalone I noticed that escaping the quotes prevents the crash ( in the original input the jq pattern itself also came from a file...

// works fine...
func main() {
	b, e := ioutil.ReadFile("plusinput.json")
	if e != nil {
		panic(e)
	}
	query, e := gojq.Parse(".items[] | .name+\"_tmp\", .id")
	if e != nil {
		panic(e)
	}
	var mint map[string]interface{}
	json.Unmarshal(b, &mint)
	iter := query.Run(mint) // or query.RunWithContext
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			log.Fatalln(err)
		}
		fmt.Printf("%#v\n", v)
	}
}

where plusinput is

{
  "items": [
    {
      "name": "myname",
      "id": "myid"
    },
    {
      "name": "yourname",
      "id": "yourid"
    }
  ]
}

**Comment by itchyny** [comment]
Please create a minimal reproduction steps.

**Comment by wader** [comment]
Seems to work with gojq https://play.golang.org/p/7HA1l7mB3Lz, could it be that you're messing up the jq expression argument somehow in the call to `gojq.Parse`?

**Comment by baileybunch5dad** [comment]
In making a minimal test case without reading files and using inline text the IDE made me behave with the quotes; the string plus operator works fine. I am closing the ticket...Thanks for the super quick response


`package main

import (
	"encoding/json"
	"fmt"
	"github.com/itchyny/gojq"
	"log"
)


func main() {
	pattern := ".items[] | .name+\"_suffix\",.id"

	jsonInput :=
	`{
		"items": [
			{
				"name": "myname",
				"id": "myid"
			},
			{
				"name": "yourname",
				"id": "yourid"
			}
		]
	}`

	q, e := gojq.Parse(pattern)
	if e != nil {
		panic(e)
	}

	b := []byte(jsonInput)
	fmt.Println(string(b))
	var mint map[string]interface{}
	json.Unmarshal(b, &mint)
	iter := q.Run(mint)
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			log.Fatalln(err)
		}
		fmt.Printf("Token %#v\n", v)
	}
}


`

**Comment by wader** [comment]
👍

**Comment by baileybunch5dad** [comment]
Also, fwiw, to make it go hiccup with
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x54e6df]

goroutine 1 [running]:
github.com/itchyny/gojq.(*compiler).compile(0xc000145290, 0x0, 0xc00016a040, 0x4d0837)
	C:/Users/chris/go/src/github.com/itchyny/gojq/compiler.go:137 +0x1df
github.com/itchyny/gojq.Compile(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/chris/go/src/github.com/itchyny/gojq/compiler.go:117 +0x1d4
github.com/itchyny/gojq.(*Query).RunWithContext(0x0, 0x0, 0x0, 0x5c9bc0, 0xc00013cff0, 0x0, 0x0)
	C:/Users/chris/go/src/github.com/itchyny/gojq/query.go:31 +0x47
github.com/itchyny/gojq.(*Query).Run(...)
	C:/Users/chris/go/src/github.com/itchyny/gojq/query.go:26
main.main()
	C:/dev/jqbug/jqbug.go:38 +0x1bd

Process finished with the exit code 2

in the 
q.Run()
if you have a silly user (sheepishly raising my hand here)
pattern := ".items[] | .name+'abc'"
that does not check the parse Parse return code (the above complaining on the single quote)
q, _ := gojq.Parse(pattern)
instead of q,e ... if e != nil 
then the Run will have above user-induced pebkac (problem exists between keyboard and chair) heartburn

`package main

import (
	"encoding/json"
	"fmt"
	"github.com/itchyny/gojq"
	"log"
)


func main() {
	//pattern := ".items[] | .name+\"_suffix\",.id"
	pattern := ".items[] | .name+'abc'"

	jsonInput :=
	`{
		"items": [
			{
				"name": "myname",
				"id": "myid"
			},
			{
				"name": "yourname",
				"id": "yourid"
			}
		]
	}`

	q, _ := gojq.Parse(pattern)
	//if e != nil {
	//	panic(e)
	//}

	b := []byte(jsonInput)
	fmt.Println(string(b))
	var mint map[string]interface{}
	json.Unmarshal(b, &mint)
	iter := q.Run(mint)
	for {
		v, ok := iter.Next()
		if !ok {
			break
		}
		if err, ok := v.(error); ok {
			log.Fatalln(err)
		}
		fmt.Printf("Token %#v\n", v)
	}
}

**Comment by wader** [comment]
Aha confusing stacktrace, go allows nil receiver and it seems `Run` does not defer the query pointer until quite late
