### ISSUE TITLE
Missing feature: $ARGS

### ISSUE THREAD

**Issue by apstndb** [itchyny/gojq#77]
gojq doesn't seem to support `$ARGS`.

```
$ jq -n '$ARGS'         
{
  "positional": [],
  "named": {}
}
```

```
$ gojq -n '$ARGS'
gojq: compile error: variable not defined: $ARGS
```

**Comment by itchyny** [comment]
That variable should be implemented with `--args` and `--jsonargs`, but they are difficult to implement with the current flag parsing package. In most real use cases `--arg` and `--jsonarg` are enough IMO.

**Comment by apstndb** [comment]
> That variable should be implemented with --args and --jsonargs, but they are difficult to implement with the current flag parsing package. In most real use cases --arg and --jsonarg are enough IMO.

`$ARGS` seems to be separated two functionality, `$ARGS.named` and `$ARGS.positional`
Actually, I don't use `--args`(`$ARGS.positional`) but use `$ARGS.named` with `--arg` and `--jsonarg` like below:

```
$ jq -n --arg name instance --arg desc "test instance" '{input: $ARGS.named, cmd: "delete \($name)"}'    
{
  "input": {
    "name": "instance",
    "desc": "test instance"
  },
  "cmd": "delete instance"
}
```

Even if `--args` and `--jsonargs` will not be implemented, `$ARGS.named` is useful. Isn't it?

**Comment by itchyny** [comment]
I implemented `$ARGS.named`, will release in a few days.
