### ISSUE TITLE
WithFunction fallback gotcha for int64s

### ISSUE THREAD

**Issue by shabbyrobe** [itchyny/gojq#78]
I'm having an issue where the comparison functions don't work properly if they are handed an int64, rather than an int. I discovered this when I tried to write a function that returned the result of time.Time.UnixNano().

Here's a minimal demonstration:

```go
func demo() {
	doStuffInt64 := func(query string, value map[string]interface{}) interface{} {
		jqp, _ := gojq.Parse(query)
		code, _ := gojq.Compile(jqp,
			gojq.WithFunction("func", 0, 0, func(x interface{}, xs []interface{}) (out interface{}) {
				return int64(x.(int))
			}),
		)
		iter := code.Run(value)
		iv, _ := iter.Next()
		return iv
	}

	// Outputs 'true' as 3000 >= 2:
	fmt.Println(doStuffInt64(`(.a|func) >= (.b|func)`, map[string]interface{}{
		"a": 3000,
		"b": 2,
	}))

	// Outputs 'true' even though 3000 <= 2:
	fmt.Println(doStuffInt64(`(.a|func) >= (.b|func)`, map[string]interface{}{
		"a": 2,
		"b": 3000,
	}))
}
```

The type switch in `binopTypeSwitch()` doesn't account for int types that aren't `int`, so the `int64` case hits `fallback()`, which compares only on type rather than value, and the result is that the code behaves incorrectly with no way of really knowing why without going for a spelunk through the source.

I believe the range of int types should be supported for comparisons, or an error should be raised when a disallowed type is encountered. I'm not very well steeped in the internals of the codebase though, maybe there's a better approach? Regardless, I think "silently behaving incorrectly" qualifies as a bug.

I am happy to have a crack at sending a PR, whatever your implementation preference, if it would be welcome.

**Comment by itchyny** [comment]
The gojq library does not support int64 type so return int or *big.Int.

**Comment by shabbyrobe** [comment]
I understand that, I should've mentioned in my original post that I've "solved" my problem by converting to one of the supported types. The problem is that the library violates the "principle of least astonishment" by silently working incorrectly in the presence of an unsupported type, and the only way to discover that was to spend an hour reading the source.

Maybe this is simply a documentation deficiency, and the docs for WithFunction should make clearer that you should not return int64, but I think that's not quite enough. I think the API should either support int64 or protect against its use, not silently work incorrectly.

**Comment by itchyny** [comment]
Sorry about that I will add notes on this, thanks.
