### ISSUE TITLE
Use posix style flags on Windows

### ISSUE THREAD

**Issue by jcwillox** [itchyny/gojq#79]
I was just trying out `gojq` and I noticed that you are using the `/` style flags on Windows, which is quite odd these days. You may want to consider switching to posix style flags on Windows for better consistency, this is what most CLI tools are doing, and I believe the `/` style flags are being phased out as both winget and the new Windows Terminal (both by Microsoft) use the `--` style flags. i.e. `/c, /compact-output` vs `-c, --compact-output`

Go-flags allows you to force the posix style flags at build time using `-tags=forceposix`
```pwsh
go build -tags=forceposix
```

**Comment by itchyny** [comment]
Hmm, I'm not familiar with Windows. Do you want me to change the behavior of executables in the releases?

**Comment by jcwillox** [comment]
You responded so quickly I didn't even see it 😄
Yeah, basically on Windows go-flags uses the old fashioned `/flag` style flags, whereas Linux uses `--flag`, go-flags allows you to disable this behaviour and use the `--flag` style on all platforms. This would be a breaking change though as currently both `gojq /yaml-output` and `gojq --yaml-output` are valid on windows, after using `-tags=forceposix`, `gojq /yaml-output` would no longer be a valid flag, the other big change is that the help menu will now reflect the posix style flags.

This is something I'd recommend doing as most tools even by Microsoft, no longer use the `/flag` style, but you may want to note that it would be breaking change for anyone using the `/flag` style.

![image](https://user-images.githubusercontent.com/39120423/121880708-ac32fd80-cd51-11eb-8cd2-54ba54e1760d.png)


![image](https://user-images.githubusercontent.com/39120423/121880645-9b828780-cd51-11eb-8712-265176358644.png)
