### ISSUE TITLE
path/1 behaviour and path expression question

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#81]
Hello, I noticed this difference from jq while trying to understand the path tracking code in gojq
```
$ jq -n '{} | path({})'
jq: error (at <unknown>): Invalid path expression with result {}
$ go run cmd/gojq/main.go -n '{} | path({})'
[]
```

Don't think i understand what the `reflect.DeepEqual` checks are doing, ex: https://github.com/itchyny/gojq/blob/main/execute.go#L226
 and https://github.com/itchyny/gojq/blob/main/execute.go#L303 i guess it's to make sure the expression was a "path" expression and did not include other things?

**Comment by itchyny** [comment]
This is due to the difference of checking the equality of path target and input value. jq checks by the pointer addresses but gojq does not. I know this problem since I implemented here but not sure there's workaround in Go, and I stopped wondering for solution because I believe there's no query which should run successfully with jq but not with gojq.

**Comment by wader** [comment]
I see, thanks for explaining. Yes i don't think it will cause any issues for me neither. I only noticed the difference while reading the code and testing different expressions.

To support doing it similar to jq I guess gojq would have to wrap all values in some struct that includes some unique value?

A bit unrelated thing I thought about while reading the code: would replace`[2]interface{}` with some struct  like `struct PathPart { key interface{}; value interface{} }` make the code clearer? ... also if go supported some kind of lightweight ADT:s it would benefit gojq i think :)

**Comment by itchyny** [comment]
It needs to wrap like that but should be recursive. But it causes various problems against `WithFunction` options.

**Comment by wader** [comment]
Ok! Thanks for the info. Closing.
