### ISSUE TITLE
Try "?" in variable expression difference to jq

### ISSUE THREAD

**Issue by wader** [itchyny/gojq#82]
Hello I noticed this difference between jq and gojq
```sh
$ jq -n '(1?) as $_ | error("a")'
$
$ go run cmd/gojq/main.go -n '(1?) as $_ | error("a")'
gojq: error: a
exit status 5
```

Same with jq 1.6 and current master. I think gojq's behaviour is what i would expect. Report as jq bug?

**Comment by itchyny** [comment]
This is a jq bug reported by https://github.com/stedolan/jq/issues/1859.

**Comment by wader** [comment]
Yes thanks!
