### ISSUE TITLE
division on integers can loose precision

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#87]
At least, that's what this example seems to show.

Setup:
```
def gcd($a; $b):
  # rgcd expects [a,b] as input
  def rgcd:
    if .[1] == 0 then .[0]
    else [.[1], (.[0] % .[1])] | rgcd
    end;
  [$a,$b] | rgcd;

def r($p;$q):
  gcd($p;$q) as $g
  | {n: ($p/$g), d: ($q/$g)} ;

def rprod($a;$b):
   $a as {n: $na, d: $da}
   | $b as {n: $nb, d: $db}
   | r( $na * $nb; $da * $db) ;

def rprod: reduce .[] as $r ( r(1;1); rprod(.; $r));

def pair:
  [{"d":1,"n":32589158477190046000},
   {"d":1,"n":59}];
```
Test case:
```
rprod(pair[0]; pair[1]),
(pair | rprod)
```
Output:
```
{"d":1,"n":1922760350154212714000}
{"d":1,"n":1.9227603501542128e+21}
```

**Comment by itchyny** [comment]
You want integer division for `%q/%g` right? Use `def intdiv($x; $y): ($x - $x % $y) / $y;`, instead of `$x / $y` as explained in README.md. Otherwise it changes floats if indivisible.

**Comment by pkoppstein** [comment]
Sorry for missing that point, and thanks for the fix.  However, here is an example showing that division of an integer by 1 causes a similar discrepancy.
```
def r($p):
  {n: $p} ;

def rprod($a;$b):
   {n: (($a.n / 1) * $b.n)};

def rprod: reduce .[] as $r ( r(1); rprod(.; $r));

def pair:
  [{"n":32589158477190046000},
   {"n":59}];

rprod(pair[0]; pair[1]),
(pair | rprod)
```
Output:
```
{"n":1922760350154212714000}
{"n":1.9227603501542128e+21}
```

**Comment by itchyny** [comment]
Okay, looks like caused by `1/1 = float64(1.0)`.

**Comment by itchyny** [comment]
Even if the divisor is 1, I don't expect program using `/` for division keeping the precision anyway. This operator in jq is floating-point division.

**Comment by itchyny** [comment]
I noticed some incosistency in my opinion. Division on big int is big int when divisible, which is important for intdiv, but int / int is always float. Worth fixing.

**Comment by itchyny** [comment]
I fixed the issue, thanks for reporting.

**Comment by pkoppstein** [comment]
@itchny - Thanks to this update, gojq is now mentioned several times at rosettacode.org. When you are so inclined, you might like to enter "gojq" in the search box there.

It would however be nice to have an official release that includes this fix so that a specific version of gojq can be mentioned, as is the custom at rosettacode.

**Comment by itchyny** [comment]
First, I appreciate your number of issue reporting greatly. I will tag a new release in coming August, please be patient.
