### ISSUE TITLE
index/1 and rindex/1 are inefficient

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#88]
Currently, gojq's builtin.jq follows jq's inefficient defs of index/1
and rindex/1, though jq's builtin.jq has a "TODO:" note about optimization.

The following is a "jq-only" approach to rectifying the problem logically (i.e., without regard
to implementation issues arising from memory management).
It is relatively complex because it attempts to replicate the existing functionality exactly,
and to replicate or improve jq's error messages.

For example, consider the bizarre error message produced by:
```
jq -n '{a:10} | index("a")'
jq: error (at <unknown>): Cannot index number with number
```
The new error message would be:
```
jq: error (at <unknown>): cannot index object with string "a"
```
### index/1
```
# Both input and $x are assumed to be of the same type, either strings or arrays
def _index_in($x):
  . as $in
  | ($x | length) as $xl
  | first( if type == "string"
           then if $x == "" then null # for conformity with jq
                else range(0; 1 + length - $xl) | select( $in[. : ] | startswith($x))
                end
           else      range(0; 1 + length - $xl) | select( $in[. : .+$xl ] == $x)
           end )
    // null;

def index($x):
  def s: # for the error message
    if type == "object" or type == "array" then ""
    elif type == "string" then " \"\(.)\""
    else " \(.)"
    end;
   def ix($y):
    . as $in
    | first( range(0; length) | select($in[.] == $y) ) // null;
    
  ($x|type) as $xt
  | type as $t
  | if $xt == $t
    then if ($xt == "array" and ($x|length) == 1) then ix($x[0])
         elif $t == "string" or $t == "array" then _index_in($x)
	 else "cannot index \($t) with \($xt)\($x|s)" | error
	 end
    elif $t == "array" then ix($x)
    else "cannot index \($t) with \($xt)\($x|s)" | error
    end ;
```
## Testing and comparing

Here are some test cases, which should be run after changing `def index` above to `def myindex`.
```
def test($in; $x):
  ([$in,$x] | debug) as $debug
  | try ($in | index($x)) catch . ,
    try ($in | myindex($x)) catch .,
    "" ;

test([0,1,2];2),
test([0,1,2];[2]),
test([0,1,2,3,4];[2,3]),
test([0,1,2];[2,3]),
test("abcdef"; []),
test("abcdef"; ""),
test("abcdef"; "c"),
test("abcdef"; "cd"),
test({a:10}; 10),

# jq gives a bizarre error message:
test({a:10}; "a")
```

**Comment by itchyny** [comment]
I'm not sure `first(range(0; 1 + length - $xl) | select($in[. : ] | startswith($x)))` is faster than `$arr1.[$arr2].[0]`. Internal functions are much faster than interpreting jq-coded implementation in general, but worth profiling.

**Comment by pkoppstein** [comment]
@itchyny - My main concern is with the intrinsic inefficiency of the builtin.jq definitions of `index` and `rindex`.  If you have the time to implement `index` efficiently in Go (that is, without using `indices`), then that would be great!

**Comment by itchyny** [comment]
Yeah, that's just what I was thinking. Accepts a value and includes no comma operator, so no need to implement in jq.

**Comment by itchyny** [comment]
The behavior of `indices/1` against objects looks wired BTW.

**Comment by pkoppstein** [comment]
I see now that the def of `_index_in` that I gave above is unsuitable for gojq because of memory management issues. 

My attempt to work around the problem seems to have uncovered another problem (https://github.com/itchyny/gojq/issues/89), so until that's resolved, I won't revise the def.

**Comment by itchyny** [comment]
Right, by _a value_ I mean a value argument...

**Comment by pkoppstein** [comment]
Thank you for attending to this so comprehensively!

One small suggestion: I noticed that you changed the "title" of this "issue" to match the commit message, but that you dropped the "ER:" prefix.  It's usually handy for everyone concerned if there is a clear distinction between the main types of "issues", which I take to be "bug reports" and "enhancement requests".  So I would suggest retaining the "ER:" in the title of enhancement requests.

**Comment by itchyny** [comment]
I have been using GitHub for almost 9 years but I didn't know what ER means! Sorry about that, but I don't think abbreviation others cannot tell its meaning...

**Comment by pkoppstein** [comment]
No doubt different communities have different conventions.  Some evidently use "[Enhancement]".  One community that uses [ER] often enough is the "Rust" community: see  https://github.com/rust-lang/rust/issues?q=%5BER%5Dbut  --- which reminds me that I was wondering if you have any thoughts on Rust as an implementation language for jq.

On ER guidelines more generally, perhaps these have some relevance:
* Oracle: https://support.oracle.com/knowledge/Oracle%20E-Business%20Suite/2018561_1.html
* Juniper: https://kb.juniper.net/InfoCenter/index?page=content&id=KB23751

**Comment by itchyny** [comment]
Thanks for links. It'll be a promising project to implement jq in Rust in various reasons; memory safety, various hashmaps in standard library (there must be a sorted map type), distributing reusable wasm library, etc. I had some ideas on implementation a few month ago, but I don't have any progress.
