### ISSUE TITLE
first/1 cannot nest itself

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#89]
Here's an implementation of `index($x)` when both the input and $x are strings:
```
def ix($x):
  . as $in
  | ($x|length) as $xl
  | first(range(0; 1 + length - $xl)
          | . as $j
	  | select( all( range(0; $xl); $in[.+$j:.+$j+1] == $x[.:.+1] )) )
    // null;
```
This works as expected with stedolan/jq, but when given the query:

    "abczcz" | ix("cz")

gojq emits both 2 and 4.

**Comment by itchyny** [comment]
Interesting issue. Looks like a nested (duplicate) label problem; here is minimal example, `first((0, 1, 2) | first(0))`.

**Comment by itchyny** [comment]
Another simple example is `isempty(first(null))`.

**Comment by itchyny** [comment]
I've fixed in my local repo, will push tonight.
