### ISSUE TITLE
bug: "unknown flag"

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#91]
Consider:
```
$ echo 10 | jq '-1 * .'
-10

$ echo 10 | gojq '-1 * .'
gojq: unknown flag `1'
```

The above transcript is from a `bash` shell.

**Comment by itchyny** [comment]
Honestly flag parsing compatibility is hard to archive; `gojq -- '-1 * .'` works but different than jq.

**Comment by itchyny** [comment]
I'm not sure the behavior of `jq -n -0 # prints -0` is correct. Both `gojq -0n` and `gojq -n0` are considered as short flags (`-0` and `-n`) with no query. It is difficult to implement the exact behavior query starting with `-`

**Comment by pkoppstein** [comment]
Maybe standard (bash-style) flag-handling is really difficult in Go?  

To minimize confusion, perhaps gojq should assume that unless the "last argument" can be interpreted as a valid flag or valid combination of flags, it should be treated as a filter:
```
$ jq -M '-.' <<< 0
-0

$ gojq -M '-.' <<< 0
gojq: unknown flag `.'
```

(As you may know, the idea that jq should allow the filter to be dropped has historically been the source of great difficulty and confusion.)

**Comment by itchyny** [comment]
Based on the go-flags library (already forked for `--arg`), I can't fix this in the near future.

**Comment by smlx** [comment]
> Maybe standard (bash-style) flag-handling is really difficult in Go?

The flag parsing in `jq` is the outlier here. Most standard (e.g. coreutils) tools do not parse flags this way. Here's an example using `cat` core coreutils:

```
$ echo foo > /tmp/foo
$ echo bar > ./-.
$ cat -v /tmp/foo -.
cat: invalid option -- '.'
Try 'cat --help' for more information.
$ cat -v -- /tmp/foo -.
foo
bar
```

**Comment by itchyny** [comment]
Right, using double dash fixes all the ambiguous arguments. I noticed there is `IgnoreUnknown` option in go-flags and it fixes some of the problems, but raises different problem that `./gojq -X` reports `function not defined: X/0` error instead of `unknown flag X`. We may fix in heuristic way.

**Comment by itchyny** [comment]
`IgnoreUnknown` option also has problem that it enables the parsed option in the leading argument; `-0 + .` should not enable the nul output option.

**Comment by itchyny** [comment]
I fixed the behavior. I hope it breaks nothing.
