### ISSUE TITLE
[ER]: --args

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#94]
```
$ jq -n '$ARGS.positional[]' --args a b c
"a"
"b"
"c"
``` 

```
$ gojq -n '$ARGS.positional[]' --args a b c
gojq: unknown flag `args'
```

**Comment by itchyny** [comment]
Based on the go-flags library, I can't implement this in the near future.

**Comment by itchyny** [comment]
This is a lack of feature but unlikely to tackle for now. I will reconsider when reimplementing flag parsing from scratch.
