### ISSUE TITLE
[Documentation] discrepancies from jq

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#95]
The README highlights important discrepancies with respect to documented jq functionality, but it would be very helpful to have a more complete inventory of discrepancies, both functional and behavioral, and perhaps distinguishing between intentional discrepancies that are likely to persist and those that are unintentional or unlikely to persist.

The README is probably not a good place for such an inventory, especially as this inventory is likely to be subject to frequent updates.  I was thinking, therefore, that the repository's wiki might be a good place to maintain such an inventory, and was wondering whether you would be open to contributions from your community of users.

**Comment by itchyny** [comment]
I will keep README cover the differences as possible. Honestly I don't like wiki of GitHub.
