### ISSUE TITLE
[bug]: include .... {"source": ...}; [discrepancy] default value of -L path

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#96]
Unfortunately, the jq specifications regarding modules are quite complex at best, so here are the relevant bits regarding the default value of the -L path:

> The default search path is the search path given to the -L command-line option, else ["~/.jq", "$ORIGIN/../lib/jq", "$ORIGIN/../lib"].

where:

> "For paths starting with "$ORIGIN/", the path of the jq executable is substituted for "$ORIGIN"."

To see the issues, consider this transcript:
```
$ cd ~/github

$ cat lib/jq/foo.jq
def foo: "This is ~/github/lib/jq/foo.jq speaking";

$ cat lib/gojq/foo.jq
def foo: "This is ~/github/lib/gojq/foo";

$ cat lib/gojq/foo.gojq
def foo: "This is ~/github/lib/gojq/foo.gojq";
```
jq works as advertised:
```
$ jqMaster/jq -nM 'include "foo"; foo'
"This is ~/github/lib/jq/foo.jq speaking"

$ jqMaster/jq -nM 'include "foo" {"search": "~/github/lib/jq"}; foo'
"This is ~/github/lib/jq/foo.jq speaking"
```
But ...
```
$ gojq/gojq -nM 'include "foo"; foo'
gojq: compile error: module not found: "foo"

$ gojq/gojq -nM 'include "foo" {"search": "~/github/lib/gojq"}; foo'
gojq: compile error: module not found: "foo"
```
Checking the files are still there:
```
$ file lib/gojq/foo.gojq
lib/gojq/foo.gojq: ASCII text

$ file lib/gojq/foo.jq
file lib/gojq/foo.jq
lib/gojq/foo.jq: ASCII text
```

So it looks like the "bug" regarding `source` is real, but maybe gojq's default search path is intentionally different?

**Comment by itchyny** [comment]
I'm confused. jq also search from the path as if `$ORIGIN` points to `$PWD`. gojq seems to follow this behavior.

**Comment by pkoppstein** [comment]
It is complex, and perhaps the varying behavior of jq over time, together with some extant bugs, makes it confusing.  Also the fact that `get_jq_origin` and `get_prog_origin` are not clearly specified does not help.

Notice, though, that in the paragraphs I quoted, there is nothing mentioned about the pwd.  Specifically:

>  "For paths starting with "$ORIGIN/", the path of the jq executable is substituted for "$ORIGIN".` 

Here, $ORIGIN is not set by the user but by the program.

Thus it's the path of the executable which is important for establishing the defaults.  Which is why I showed these paths in the transcript.

Anyway, setting aside the issues with the default path, there's the more pressing problem regarding "source".

(By the way, for the sake of everyone's sanity, I would suggest you reconsider supporting those three `get_*` filters.)

**Comment by itchyny** [comment]
`$ORIGIN` is the directory of the jq executable, not the path of executable, right?

**Comment by itchyny** [comment]
I thought it's easy to prefix the absolute directory of the executable but
```sh
~/github
❯ jqMaster/jq -nM get_jq_origin
"jqMaster"

~/github
❯ jqMaster/jq -nM 'include "foo"; foo'
"This is ~/github/lib/jq/foo.jq speaking"

~/github
❯ export PATH=~/github/jqMaster:$PATH

~/github
❯ which jq
/Users/itchyny/github/jqMaster/jq

~/github
❯ jq -nM 'include "foo"; foo'
jq: error: module not found: foo

jq: 1 compile error
```
This confusing behavior is not worth reproduce in gojq.

**Comment by pkoppstein** [comment]
@itchyny - As discussed, there are some discrepancies between jq and gojq with respect to the algorithms for locating "modules", but  as of this writing, gojq's README page does not seem to include the relevant details, either in the form of a description of gojq's intended behavior, or in the form of a description of the main discrepancies.    

In my experience to date, the main areas of apparently-intended discrepancies are:

(1) the significance of "ORIGIN" with respect to the default library path (ORIGIN referring to the directory where the executable has been installed); and

(2) the algorithm for locating a module that is included or imported in a particular file in a particular directory.

**Comment by itchyny** [comment]
- The problem is, jq does not implement what it says in the document. `$ORIGIN` is not the path of the jq executable, but the directory the executable locates
- But it uses `argv[0]` to get the executable location, so it only works when the executable is invoked by specifying the exact executable path
- Thus the origin is the current working directory when the program is invoked by the command name only, as most user do. this behavior looks not useful, the default library path should not change. Are you really install libraries in `$ORIGIN/lib`?
- Considering these behaviors, even if gojq fixes to use `$ORIGIN` as the absolute directory where the executable locates, it creates a new discrepancy. You want me to use `os.Args[0]` like jq does?

```
 % jq -n get_jq_origin
"."
 % ls ./jq
"./jq": No such file or directory (os error 2)
 % `which jq` -n get_jq_origin
"/opt/homebrew/bin"
```

**Comment by pkoppstein** [comment]
@itchyny -

Let's start with the manual, which states:

   `For paths starting with "$ORIGIN/", the path of the jq executable is substituted for "$ORIGIN".`

Here, "path" does not mean the same as "pathname"; it means, in effect, the path *to* the jq executable,
i.e. the pathname of the folder in which the jq executable exists.

In any case, what's important is that if jq ships with jq modules in a folder, then
the defaults should be such that `include` and `import` directives should be able to find them

This was the idea behind ORIGIN. Specifically, let's suppose that
$ORIGIN is the pathname of the directory in which the jq executable
exists.  Then the jq-provided modules (files) would live in
$ORIGIN/lib/ or $ORIGIN/lib/jq and the defaults should be such that
executing $ORIGIN/jq will ensure that the modules will be found when
not overridden in some way.

Apart possibly from some relatively unimportant subtleties, jqMaster actually works this way.

**Comment by itchyny** [comment]
Considering fixing the discrepancy, should it be `$ORIGIN/../lib/jq` or `$ORIGIN/../lib/gojq`?

**Comment by pkoppstein** [comment]
Logically, I think it would have to be $ORIGIN/../lib/gojq for the reason that you have
evidently already considered, namely because if jq ever has a "lib"
directory, then some package managers would probably want to put it in
$ORIGIN/../lib/jq.  

This might be expected, for example, if $ORIGIN is /usr/local/bin/

Fortunately, modern package managers tend to avoid this problem,
e.g. on my machine, asdf installs the jq 1.6 executable as

    ~/.asdf/installs/jq/1.6/bin/jq

**Comment by itchyny** [comment]
I have finally changed the default module paths. Thanks for patient explanation.
